export const symbols = [
  {
    category: "Stars",
    items: [
      { id: 1, name: "Black Star", symbol: "★" },
      { id: 2, name: "White Star", symbol: "☆" },
      { id: 3, name: "Star of David", symbol: "✡" },
      { id: 4, name: "Four Pointed Star", symbol: "✦" },
      { id: 5, name: "Eight Pointed Star", symbol: "✧" },
      { id: 6, name: "Circled Star", symbol: "✩" },
      { id: 7, name: "Circled White Star", symbol: "✪" },
      { id: 8, name: "Heavy Star", symbol: "✫" },
      { id: 9, name: "Heavy Star With White Center", symbol: "✬" },
      { id: 10, name: "Six Pointed Star", symbol: "✭" },
      { id: 11, name: "Solid Star", symbol: "✮" },
      { id: 12, name: "Open Star", symbol: "✯" },
      { id: 13, name: "Star with Circled Circle", symbol: "✰" },
      { id: 14, name: "Asterism", symbol: "⁂" },
      { id: 15, name: "Heavy Asterisk", symbol: "⁎" },
      { id: 16, name: "Reference Mark", symbol: "⁑" },
      { id: 17, name: "Heavy Circle with Star", symbol: "✢" },
      { id: 18, name: "Circle With Star", symbol: "✣" },
      { id: 19, name: "Star in Circle", symbol: "✤" },
      { id: 20, name: "Circle with Star Right Half", symbol: "✥" },
      { id: 21, name: "White Star", symbol: "✱" },
      { id: 22, name: "Black Star", symbol: "✲" },
      { id: 23, name: "Comet Star", symbol: "✳" },
      { id: 24, name: "Circled Black Star", symbol: "✴" },
      { id: 25, name: "Circled Star Left Half", symbol: "✵" },
      { id: 26, name: "Eight-Pointed Star", symbol: "✶" },
      { id: 27, name: "Asterisk Star", symbol: "✷" },
      { id: 28, name: "Star with Outlined Center", symbol: "✸" },
      { id: 29, name: "Star with Outer Radiant", symbol: "✹" },
      { id: 30, name: "Pointed Star", symbol: "✺" },
      { id: 31, name: "Circled Star Inside", symbol: "✻" },
      { id: 32, name: "Circled Star Outlined", symbol: "✼" },
      { id: 33, name: "Heavy Star with Ring", symbol: "✽" },
      { id: 34, name: "Fleur-de-Lis", symbol: "✾" },
      { id: 35, name: "White Star Inside Circle", symbol: "✿" },
      { id: 36, name: "Flower Symbol", symbol: "❀" },
      { id: 37, name: "Circled Flower", symbol: "❁" },
      { id: 38, name: "Open Flower", symbol: "❂" },
      { id: 39, name: "Solid Flower", symbol: "❃" },
      { id: 40, name: "Circle with Symbol", symbol: "❇" },
      { id: 41, name: "Snowflake", symbol: "❈" },
      { id: 42, name: "White Snowflake", symbol: "❉" },
      { id: 43, name: "Snowflake Inside Circle", symbol: "❊" },
      { id: 44, name: "Snowflake Inside Star", symbol: "❋" },
      { id: 45, name: "Star with Flake", symbol: "❄" },
      { id: 46, name: "Cold Star", symbol: "❆" },
      { id: 47, name: "Frosted Star", symbol: "❅" },
      { id: 48, name: "Small Star", symbol: "⋆" },
      { id: 49, name: "Emblem Star", symbol: "≛" },
      { id: 50, name: "Celtic Star", symbol: "ᕯ" },
      { id: 51, name: "Sparkling Star", symbol: "✲" },
      { id: 52, name: "Ritual Star", symbol: "࿏" },
      { id: 53, name: "Faded Star", symbol: "꙰" },
      { id: 54, name: "Moonlit Star", symbol: "۞" },
      { id: 55, name: "Celestial Star", symbol: "⭒" },
      { id: 56, name: "Eclipse Star", symbol: "⍟" },
      { id: 57, name: "Star Emoji", symbol: "⭐" },
      { id: 58, name: "Meteor Star", symbol: "🌠" },
      { id: 59, name: "Glowing Star", symbol: "🌟" },
      { id: 60, name: "Sparkle Star", symbol: "💫" },
      { id: 61, name: "Shining Star", symbol: "✨" },
      { id: 62, name: "Night Sky Star", symbol: "🌃" },
      { id: 63, name: "Astrological Star", symbol: "🔯" },
    ],
  },
  {
    category: "Office & Law",
    items: [
      { id: 64, name: "Copyright", symbol: "©" },
      { id: 65, name: "Registered Trademark", symbol: "®" },
      { id: 66, name: "Trademark", symbol: "™" },
      { id: 67, name: "Service Mark", symbol: "℠" },
      { id: 68, name: "Telephone Sign", symbol: "℡" },
      { id: 69, name: "Phonograph Copyright", symbol: "℗" },
      { id: 70, name: "Per Mille", symbol: "‱" },
      { id: 71, name: "Number Sign", symbol: "№" },
      { id: 72, name: "Commercial At", symbol: "℀" },
      { id: 73, name: "Account Of", symbol: "℁" },
      { id: 74, name: "Care Of", symbol: "℅" },
      { id: 75, name: "Celsius", symbol: "℆" },
      { id: 76, name: "Turned Ampersand", symbol: "⅍" },
      { id: 77, name: "Ascending Node", symbol: "☊" },
      { id: 78, name: "Telephone", symbol: "☎" },
      { id: 79, name: "Filling Telephone", symbol: "☏" },
      { id: 80, name: "Keyboard", symbol: "⌨" },
      { id: 81, name: "File Folder", symbol: "✁" },
      { id: 82, name: "Scissors", symbol: "✂" },
      { id: 83, name: "Clipboard", symbol: "✃" },
      { id: 84, name: "Writing Hand", symbol: "✄" },
      { id: 85, name: "Telephone Receiver", symbol: "✆" },
      { id: 86, name: "Envelope", symbol: "✇" },
      { id: 87, name: "Airplane", symbol: "✈" },
      { id: 88, name: "Envelope with Downwards Arrow", symbol: "✉" },
      { id: 89, name: "Writing Hand", symbol: "✎" },
      { id: 90, name: "Pencil", symbol: "✏" },
      { id: 91, name: "Writing Pen", symbol: "✐" },
      { id: 92, name: "Writing Brush", symbol: "✑" },
      { id: 93, name: "Fountain Pen", symbol: "✒" },
      { id: 94, name: "Per Thousand", symbol: "‰" },
      { id: 95, name: "Section", symbol: "§" },
      { id: 96, name: "Paragraph", symbol: "¶" },
      { id: 97, name: "Victory Hand", symbol: "✌️" },
      { id: 98, name: "Backhand Index Pointing Up", symbol: "☝️" },
      { id: 99, name: "Rightwards Arrow", symbol: "☞" },
      { id: 100, name: "Black Right Pointing Triangle", symbol: "☛" },
      { id: 101, name: "Black Down Pointing Triangle", symbol: "☟" },
      { id: 102, name: "Leftwards Arrow", symbol: "☜" },
      { id: 103, name: "Black Left Pointing Triangle", symbol: "☚" },
      { id: 104, name: "Writing Hand", symbol: "✍️" },
    ],
  },
  {
    category: "Currency",
    items: [
      { id: 105, name: "Cent", symbol: "¢" },
      { id: 106, name: "Dollar", symbol: "$" },
      { id: 107, name: "Euro", symbol: "€" },
      { id: 108, name: "Pound Sterling", symbol: "£" },
      { id: 109, name: "Yen/Yuan", symbol: "¥" },
      { id: 110, name: "Tugrik", symbol: "₮" },
      { id: 111, name: "Bengali Rupee (Mark)", symbol: "৲" },
      { id: 112, name: "Bengali Rupee", symbol: "৳" },
      { id: 113, name: "Tamil Rupee", symbol: "௹" },
      { id: 114, name: "Baht", symbol: "฿" },
      { id: 115, name: "Riel", symbol: "៛" },
      { id: 116, name: "Euro-Currency Sign", symbol: "₠" },
      { id: 117, name: "Colon Sign", symbol: "₡" },
      { id: 118, name: "Cruzeiro Sign", symbol: "₢" },
      { id: 119, name: "French Franc Sign", symbol: "₣" },
      { id: 120, name: "Lira Sign", symbol: "₤" },
      { id: 121, name: "Mill Sign", symbol: "₥" },
      { id: 122, name: "Naira Sign", symbol: "₦" },
      { id: 123, name: "Peseta Sign", symbol: "₧" },
      { id: 124, name: "Rupee Sign", symbol: "₨" },
      { id: 125, name: "Won Sign", symbol: "₩" },
      { id: 126, name: "New Sheqel Sign", symbol: "₪" },
      { id: 127, name: "Dong Sign", symbol: "₫" },
      { id: 128, name: "Kip Sign", symbol: "₭" },
      { id: 129, name: "Drachma Sign", symbol: "₯" },
      { id: 130, name: "German Penny Sign", symbol: "₰" },
      { id: 131, name: "Peso Sign", symbol: "₱" },
      { id: 132, name: "Guarani Sign", symbol: "₲" },
      { id: 133, name: "Austral Sign", symbol: "₳" },
      { id: 134, name: "Hryvnia Sign", symbol: "₴" },
      { id: 135, name: "Cedi Sign", symbol: "₵" },
      { id: 136, name: "Yen/Yuan Character", symbol: "￥" },
      { id: 137, name: "Rial Sign", symbol: "﷼" },
      { id: 138, name: "Currency Sign", symbol: "¤" },
      { id: 139, name: "Florin/Guilder", symbol: "ƒ" },
    ],
  },
  {
    category: "Bracket",
    items: [
      { id: 140, name: "Angle Bracket Left", symbol: "〈" },
      { id: 141, name: "Angle Bracket Right", symbol: "〉" },
      { id: 142, name: "Double Angle Bracket Left", symbol: "《" },
      { id: 143, name: "Double Angle Bracket Right", symbol: "》" },
      { id: 144, name: "Corner Bracket Left", symbol: "「" },
      { id: 145, name: "Corner Bracket Right", symbol: "」" },
      { id: 146, name: "White Corner Bracket Left", symbol: "『" },
      { id: 147, name: "White Corner Bracket Right", symbol: "』" },
      { id: 148, name: "Black Lenticular Bracket Left", symbol: "【" },
      { id: 149, name: "Black Lenticular Bracket Right", symbol: "】" },
      { id: 150, name: "Tortoise Shell Bracket Left", symbol: "〔" },
      { id: 151, name: "Tortoise Shell Bracket Right", symbol: "〕" },
      {
        id: 152,
        name: "Presentation Form for Vertical Parenthesis Left",
        symbol: "︵",
      },
      {
        id: 153,
        name: "Presentation Form for Vertical Parenthesis Right",
        symbol: "︶",
      },
      {
        id: 154,
        name: "Presentation Form for Vertical Curly Bracket Left",
        symbol: "︷",
      },
      {
        id: 155,
        name: "Presentation Form for Vertical Curly Bracket Right",
        symbol: "︸",
      },
      {
        id: 156,
        name: "Presentation Form for Vertical Tortoise Shell Bracket Left",
        symbol: "︹",
      },
      {
        id: 157,
        name: "Presentation Form for Vertical Tortoise Shell Bracket Right",
        symbol: "︺",
      },
      {
        id: 158,
        name: "Presentation Form for Vertical Black Lenticular Bracket Left",
        symbol: "︻",
      },
      {
        id: 159,
        name: "Presentation Form for Vertical Black Lenticular Bracket Right",
        symbol: "︼",
      },
      {
        id: 160,
        name: "Presentation Form for Vertical Double Angle Bracket Left",
        symbol: "︽",
      },
      {
        id: 161,
        name: "Presentation Form for Vertical Double Angle Bracket Right",
        symbol: "︾",
      },
      {
        id: 162,
        name: "Presentation Form for Vertical Angle Bracket Left",
        symbol: "︿",
      },
      {
        id: 163,
        name: "Presentation Form for Vertical Angle Bracket Right",
        symbol: "﹀",
      },
      {
        id: 164,
        name: "Presentation Form for Vertical Corner Bracket Left",
        symbol: "﹁",
      },
      {
        id: 165,
        name: "Presentation Form for Vertical Corner Bracket Right",
        symbol: "﹂",
      },
      {
        id: 166,
        name: "Presentation Form for Vertical White Corner Bracket Left",
        symbol: "﹃",
      },
      {
        id: 167,
        name: "Presentation Form for Vertical White Corner Bracket Right",
        symbol: "﹄",
      },
      { id: 168, name: "Small Parenthesis Left", symbol: "﹙" },
      { id: 169, name: "Small Parenthesis Right", symbol: "﹚" },
      { id: 170, name: "Small Curly Bracket Left", symbol: "﹛" },
      { id: 171, name: "Small Curly Bracket Right", symbol: "﹜" },
      { id: 172, name: "Small Tortoise Shell Bracket Left", symbol: "﹝" },
      { id: 173, name: "Small Tortoise Shell Bracket Right", symbol: "﹞" },
      { id: 174, name: "Small Angle Bracket Left", symbol: "﹤" },
      { id: 175, name: "Small Angle Bracket Right", symbol: "﹥" },
      { id: 176, name: "Fullwidth Parenthesis Left", symbol: "（" },
      { id: 177, name: "Fullwidth Parenthesis Right", symbol: "）" },
      { id: 178, name: "Fullwidth Less-Than Sign", symbol: "＜" },
      { id: 179, name: "Fullwidth Greater-Than Sign", symbol: "＞" },
      { id: 180, name: "Fullwidth Curly Bracket Left", symbol: "｛" },
      { id: 181, name: "Fullwidth Curly Bracket Right", symbol: "｝" },
      { id: 182, name: "Double Bracket Left", symbol: "〖" },
      { id: 183, name: "Double Bracket Right", symbol: "〗" },
      { id: 184, name: "Heavy Double Bracket Left", symbol: "〘" },
      { id: 185, name: "Heavy Double Bracket Right", symbol: "〙" },
      { id: 186, name: "Heavy Angle Bracket Left", symbol: "〚" },
      { id: 187, name: "Heavy Angle Bracket Right", symbol: "〛" },
      { id: 188, name: "Double Angle Quotation Mark Left", symbol: "«" },
      { id: 189, name: "Double Angle Quotation Mark Right", symbol: "»" },
      { id: 190, name: "Single Angle Quotation Mark Left", symbol: "‹" },
      { id: 191, name: "Single Angle Quotation Mark Right", symbol: "›" },
      { id: 192, name: "Mathematical Angle Bracket Left", symbol: "〈" },
      { id: 193, name: "Mathematical Angle Bracket Right", symbol: "〉" },
      { id: 194, name: "Vertical Kana Repeat Mark", symbol: "〱" },
    ],
  },
  {
    category: "Chess Card",
    items: [
      { id: 195, name: "White Chess King", symbol: "♔" },
      { id: 196, name: "White Chess Queen", symbol: "♕" },
      { id: 197, name: "White Chess Rook", symbol: "♖" },
      { id: 198, name: "White Chess Bishop", symbol: "♗" },
      { id: 199, name: "White Chess Knight", symbol: "♘" },
      { id: 200, name: "White Chess Pawn", symbol: "♙" },
      { id: 201, name: "Black Chess King", symbol: "♚" },
      { id: 202, name: "Black Chess Queen", symbol: "♛" },
      { id: 203, name: "Black Chess Rook", symbol: "♜" },
      { id: 204, name: "Black Chess Bishop", symbol: "♝" },
      { id: 205, name: "Black Chess Knight", symbol: "♞" },
      { id: 206, name: "Black Chess Pawn", symbol: "♟" },
      { id: 207, name: "White Spade Suit", symbol: "♤" },
      { id: 208, name: "Black Spade Suit", symbol: "♠" },
      { id: 209, name: "White Club Suit", symbol: "♧" },
      { id: 210, name: "Black Club Suit", symbol: "♣" },
      { id: 211, name: "White Heart Suit", symbol: "♡" },
      { id: 212, name: "Black Heart Suit", symbol: "♥" },
      { id: 213, name: "White Diamond Suit", symbol: "♢" },
      { id: 214, name: "Black Diamond Suit", symbol: "♦" },
    ],
  },
  {
    category: "Musical Notes",
    items: [
      { id: 215, name: "Quarter Note", symbol: "♩" },
      { id: 216, name: "Eighth Note", symbol: "♪" },
      { id: 217, name: "Beamed Eighth Notes", symbol: "♫" },
      { id: 218, name: "Beamed Sixteenth Notes", symbol: "♬" },
      { id: 219, name: "Music Flat Sign", symbol: "♭" },
      { id: 220, name: "Music Natural Sign", symbol: "♮" },
      { id: 221, name: "Music Sharp Sign", symbol: "♯" },
      { id: 222, name: "Degree Sign", symbol: "°" },
      { id: 223, name: "Empty Set", symbol: "ø" },
      { id: 224, name: "Arabic Musical Symbol Half Flat", symbol: "؂" },
      { id: 225, name: "Not Equal To", symbol: "≠" },
      {
        id: 226,
        name: "Neither Approximately Nor Actually Equal To",
        symbol: "≭",
      },
    ],
  },
  {
    category: "Degree Weather Unit",
    items: [
      { id: 227, name: "Degree Sign", symbol: "°" },
      { id: 228, name: "Degree Celsius", symbol: "℃" },
      { id: 229, name: "Degree Fahrenheit", symbol: "℉" },
      { id: 230, name: "Greek Kappa Symbol", symbol: "ϟ" },
      { id: 231, name: "Black Sun With Rays", symbol: "☀" },
      { id: 232, name: "Cloud", symbol: "☁" },
      { id: 233, name: "Umbrella", symbol: "☂" },
      { id: 234, name: "Snowman", symbol: "☃" },
      { id: 235, name: "Sun", symbol: "☉" },
      { id: 236, name: "White Sun With Rays", symbol: "☼" },
      { id: 237, name: "First Quarter Moon", symbol: "☽" },
      { id: 238, name: "Last Quarter Moon", symbol: "☾" },
      { id: 239, name: "Earth", symbol: "♁" },
      { id: 240, name: "Hot Springs", symbol: "♨" },
      { id: 241, name: "Snowflake", symbol: "❄" },
      { id: 242, name: "Thin Snowflake", symbol: "❅" },
      { id: 243, name: "Heavy Snowflake", symbol: "❆" },
      { id: 244, name: "Lightning", symbol: "☇" },
      { id: 245, name: "Lightning With Rain", symbol: "☈" },
      { id: 246, name: "Comet", symbol: "☄" },
      { id: 247, name: "Milligram", symbol: "㎎" },
      { id: 248, name: "Kilogram", symbol: "㎏" },
      { id: 249, name: "Millimeter", symbol: "㎜" },
      { id: 250, name: "Centimeter", symbol: "㎝" },
      { id: 251, name: "Kilometer", symbol: "㎞" },
      { id: 252, name: "Square Meter", symbol: "㎡" },
      { id: 253, name: "Cubic Centimeter", symbol: "㏄" },
      { id: 254, name: "Square Km", symbol: "㏎" },
      { id: 255, name: "Natural Logarithm", symbol: "㏑" },
      { id: 256, name: "Logarithm", symbol: "㏒" },
      { id: 257, name: "Estimated Symbol", symbol: "㏕" },
    ],
  },
  {
    category: "Arrow",
    items: [
      { id: 258, name: "Up Down Arrow", symbol: "↕" },
      { id: 259, name: "North West Arrow", symbol: "↖" },
      { id: 260, name: "North East Arrow", symbol: "↗" },
      { id: 261, name: "South East Arrow", symbol: "↘" },
      { id: 262, name: "South West Arrow", symbol: "↙" },
      { id: 263, name: "Leftwards Arrow With Stroke", symbol: "↚" },
      { id: 264, name: "Rightwards Arrow With Stroke", symbol: "↛" },
      { id: 265, name: "Leftwards Wave Arrow", symbol: "↜" },
      { id: 266, name: "Rightwards Wave Arrow", symbol: "↝" },
      { id: 267, name: "Leftwards Two Headed Arrow", symbol: "↞" },
      { id: 268, name: "Upwards Two Headed Arrow", symbol: "↟" },
      { id: 269, name: "Rightwards Two Headed Arrow", symbol: "↠" },
      { id: 270, name: "Downwards Two Headed Arrow", symbol: "↡" },
      { id: 271, name: "Leftwards Arrow With Tail", symbol: "↢" },
      { id: 272, name: "Rightwards Arrow With Tail", symbol: "↣" },
      { id: 273, name: "Leftwards Arrow From Bar", symbol: "↤" },
      { id: 274, name: "Upwards Arrow From Bar", symbol: "↥" },
      { id: 275, name: "Rightwards Arrow From Bar", symbol: "↦" },
      { id: 276, name: "Downwards Arrow From Bar", symbol: "↧" },
      { id: 277, name: "Up Down Arrow With Base", symbol: "↨" },
      { id: 278, name: "Leftwards Arrow With Hook", symbol: "↩" },
      { id: 279, name: "Rightwards Arrow With Hook", symbol: "↪" },
      { id: 280, name: "Leftwards Arrow With Loop", symbol: "↫" },
      { id: 281, name: "Rightwards Arrow With Loop", symbol: "↬" },
      { id: 282, name: "Left Right Wave Arrow", symbol: "↭" },
      { id: 283, name: "Left Right Arrow With Stroke", symbol: "↮" },
      { id: 284, name: "Downwards Zigzag Arrow", symbol: "↯" },
      { id: 285, name: "Upwards Arrow With Tip Leftwards", symbol: "↰" },
      { id: 286, name: "Upwards Arrow With Tip Rightwards", symbol: "↱" },
      { id: 287, name: "Downwards Arrow With Tip Leftwards", symbol: "↲" },
      { id: 288, name: "Downwards Arrow With Tip Rightwards", symbol: "↳" },
      { id: 289, name: "Rightwards Arrow With Corner Downwards", symbol: "↴" },
      { id: 290, name: "Anticlockwise Top Semicircle Arrow", symbol: "↶" },
      { id: 291, name: "Clockwise Top Semicircle Arrow", symbol: "↷" },
      { id: 292, name: "North West Arrow To Long Bar", symbol: "↸" },
      {
        id: 293,
        name: "Leftwards Arrow To Bar Over Rightwards Arrow To Bar",
        symbol: "↹",
      },
      { id: 294, name: "Anticlockwise Open Circle Arrow", symbol: "↺" },
      { id: 295, name: "Clockwise Open Circle Arrow", symbol: "↻" },
      { id: 296, name: "Leftwards Harpoon With Barb Upwards", symbol: "↼" },
      { id: 297, name: "Leftwards Harpoon With Barb Downwards", symbol: "↽" },
      { id: 298, name: "Upwards Harpoon With Barb Rightwards", symbol: "↾" },
      { id: 299, name: "Upwards Harpoon With Barb Leftwards", symbol: "↿" },
      { id: 300, name: "Rightwards Harpoon With Barb Upwards", symbol: "⇀" },
      { id: 301, name: "Rightwards Harpoon With Barb Downwards", symbol: "⇁" },
      { id: 302, name: "Downwards Harpoon With Barb Rightwards", symbol: "⇂" },
      { id: 303, name: "Downwards Harpoon With Barb Leftwards", symbol: "⇃" },
      { id: 304, name: "Rightwards Arrow Over Leftwards Arrow", symbol: "⇄" },
      {
        id: 305,
        name: "Upwards Arrow Leftwards Of Downwards Arrow",
        symbol: "⇅",
      },
      { id: 306, name: "Leftwards Arrow Over Rightwards Arrow", symbol: "⇆" },
      { id: 307, name: "Leftwards Paired Arrows", symbol: "⇇" },
      { id: 308, name: "Upwards Paired Arrows", symbol: "⇈" },
      { id: 309, name: "Rightwards Paired Arrows", symbol: "⇉" },
      { id: 310, name: "Downwards Paired Arrows", symbol: "⇊" },
      {
        id: 311,
        name: "Leftwards Harpoon Over Rightwards Harpoon",
        symbol: "⇋",
      },
      {
        id: 312,
        name: "Rightwards Harpoon Over Leftwards Harpoon",
        symbol: "⇌",
      },
      { id: 313, name: "Leftwards Double Arrow With Stroke", symbol: "⇍" },
      { id: 314, name: "Left Right Double Arrow With Stroke", symbol: "⇎" },
      { id: 315, name: "Rightwards Double Arrow With Stroke", symbol: "⇏" },
      { id: 316, name: "Up Down Double Arrow", symbol: "⇕" },
      { id: 317, name: "North West Double Arrow", symbol: "⇖" },
      { id: 318, name: "North East Double Arrow", symbol: "⇗" },
      { id: 319, name: "South East Double Arrow", symbol: "⇘" },
      { id: 320, name: "South West Double Arrow", symbol: "⇙" },
      { id: 321, name: "Leftwards Triple Arrow", symbol: "⇚" },
      { id: 322, name: "Rightwards Triple Arrow", symbol: "⇛" },
      { id: 323, name: "Leftwards Squiggle Arrow", symbol: "⇜" },
      { id: 324, name: "Rightwards Squiggle Arrow", symbol: "⇝" },
      { id: 325, name: "Upwards Arrow With Double Stroke", symbol: "⇞" },
      { id: 326, name: "Downwards Arrow With Double Stroke", symbol: "⇟" },
      { id: 327, name: "Leftwards Dashed Arrow", symbol: "⇠" },
      { id: 328, name: "Upwards Dashed Arrow", symbol: "⇡" },
      { id: 329, name: "Rightwards Dashed Arrow", symbol: "⇢" },
      { id: 330, name: "Downwards Dashed Arrow", symbol: "⇣" },
      { id: 331, name: "Leftwards Arrow To Bar", symbol: "⇤" },
      { id: 332, name: "Rightwards Arrow To Bar", symbol: "⇥" },
      { id: 333, name: "Leftwards White Arrow", symbol: "⇦" },
      { id: 334, name: "Upwards White Arrow", symbol: "⇧" },
      { id: 335, name: "Rightwards White Arrow", symbol: "⇨" },
      { id: 336, name: "Downwards White Arrow", symbol: "⇩" },
      { id: 337, name: "Upwards White Arrow From Bar", symbol: "⇪" },
      { id: 338, name: "Projective", symbol: "⌅" },
      { id: 339, name: "Perspective", symbol: "⌆" },
      { id: 340, name: "Enter Key", symbol: "⌤" },
      { id: 341, name: "Return Symbol", symbol: "⏎" },
      { id: 342, name: "Black Right-Pointing Triangle", symbol: "▶" },
      { id: 343, name: "Lightning", symbol: "☇" },
      { id: 344, name: "Lightning With Rain", symbol: "☈" },
      { id: 345, name: "Conjunction", symbol: "☊" },
      { id: 346, name: "Opposition", symbol: "☋" },
      { id: 347, name: "Ascending Node", symbol: "☌" },
      { id: 348, name: "Descending Node", symbol: "☍" },
      { id: 349, name: "Heavy Wide-Headed Rightwards Arrow", symbol: "➔" },
      { id: 350, name: "Heavy South East Arrow", symbol: "➘" },
      { id: 351, name: "Heavy Rightwards Arrow", symbol: "➙" },
      { id: 352, name: "Heavy North East Arrow", symbol: "➚" },
      { id: 353, name: "Drafting Point Rightwards Arrow", symbol: "➛" },
      { id: 354, name: "Heavy Round-Tipped Rightwards Arrow", symbol: "➜" },
      { id: 355, name: "Triangle-Headed Rightwards Arrow", symbol: "➝" },
      { id: 356, name: "Heavy Triangle-Headed Rightwards Arrow", symbol: "➞" },
      { id: 357, name: "Dashed Triangle-Headed Rightwards Arrow", symbol: "➟" },
      {
        id: 358,
        name: "Heavy Dashed Triangle-Headed Rightwards Arrow",
        symbol: "➠",
      },
      { id: 359, name: "Black Rightwards Arrow", symbol: "➡" },
      {
        id: 360,
        name: "Three-D Top-Lighted Rightwards Arrowhead",
        symbol: "➢",
      },
      {
        id: 361,
        name: "Three-D Bottom-Lighted Rightwards Arrowhead",
        symbol: "➣",
      },
      { id: 362, name: "Black Rightwards Arrowhead", symbol: "➤" },
      {
        id: 363,
        name: "Heavy Black Curved Downwards And Rightwards Arrow",
        symbol: "➥",
      },
      {
        id: 364,
        name: "Heavy Black Curved Upwards And Rightwards Arrow",
        symbol: "➦",
      },
      { id: 365, name: "Squat Black Rightwards Arrow", symbol: "➧" },
      {
        id: 366,
        name: "Heavy Concave-Pointed Black Rightwards Arrow",
        symbol: "➨",
      },
      { id: 367, name: "Right-Shaded White Rightwards Arrow", symbol: "➩" },
      { id: 368, name: "Left-Shaded White Rightwards Arrow", symbol: "➪" },
      {
        id: 369,
        name: "Back-Tilted Shadowed White Rightwards Arrow",
        symbol: "➫",
      },
      {
        id: 370,
        name: "Front-Tilted Shadowed White Rightwards Arrow",
        symbol: "➬",
      },
      {
        id: 371,
        name: "Heavy Lower Right-Shadowed White Rightwards Arrow",
        symbol: "➭",
      },
      {
        id: 372,
        name: "Heavy Upper Right-Shadowed White Rightwards Arrow",
        symbol: "➮",
      },
      {
        id: 373,
        name: "Notched Lower Right-Shadowed White Rightwards Arrow",
        symbol: "➯",
      },
      {
        id: 374,
        name: "Notched Upper Right-Shadowed White Rightwards Arrow",
        symbol: "➱",
      },
      { id: 375, name: "Circled Heavy White Rightwards Arrow", symbol: "➲" },
      { id: 376, name: "White-Feathered Rightwards Arrow", symbol: "➳" },
      { id: 377, name: "Black-Feathered South East Arrow", symbol: "➴" },
      { id: 378, name: "Black-Feathered Rightwards Arrow", symbol: "➵" },
      { id: 379, name: "Black-Feathered North East Arrow", symbol: "➶" },
      { id: 380, name: "Heavy Black-Feathered South East Arrow", symbol: "➷" },
      { id: 381, name: "Heavy Black-Feathered Rightwards Arrow", symbol: "➸" },
      { id: 382, name: "Heavy Black-Feathered North East Arrow", symbol: "➹" },
      { id: 383, name: "Teardrop-Barbed Rightwards Arrow", symbol: "➺" },
      { id: 384, name: "Heavy Teardrop-Shanked Rightwards Arrow", symbol: "➻" },
      { id: 385, name: "Wedge-Tailed Rightwards Arrow", symbol: "➼" },
      { id: 386, name: "Heavy Wedge-Tailed Rightwards Arrow", symbol: "➽" },
      { id: 387, name: "Open-Outlined Rightwards Arrow", symbol: "➾" },
      {
        id: 388,
        name: "Arrow Pointing Rightwards Then Curving Upwards",
        symbol: "⤴",
      },
      {
        id: 389,
        name: "Arrow Pointing Rightwards Then Curving Downwards",
        symbol: "⤵",
      },
      { id: 390, name: "Downwards Arrow With Corner Leftwards", symbol: "↵" },
      { id: 391, name: "Downwards Arrow", symbol: "↓" },
      { id: 392, name: "Left Right Arrow", symbol: "↔" },
      { id: 393, name: "Leftwards Arrow", symbol: "←" },
      { id: 394, name: "Rightwards Arrow", symbol: "→" },
      { id: 395, name: "Upwards Arrow", symbol: "↑" },
      { id: 396, name: "Delete To The Right", symbol: "⌦" },
      { id: 397, name: "Delete To The Left", symbol: "⌫" },
      { id: 398, name: "Clear", symbol: "⌧" },
      { id: 399, name: "White Arrow Shaft Width One", symbol: "⇰" },
      { id: 400, name: "White Arrow Shaft Width Two Thirds", symbol: "⇫" },
      { id: 401, name: "White Arrow Shaft Width One Half", symbol: "⇬" },
      { id: 402, name: "White Arrow Shaft Width One Third", symbol: "⇭" },
      { id: 403, name: "White Arrow Shaft Width One Quarter", symbol: "⇳" },
      { id: 404, name: "White Arrow Shaft Width One Fifth", symbol: "⇮" },
      { id: 405, name: "White Arrow Shaft Width One Sixth", symbol: "⇯" },
      { id: 406, name: "White Arrow Shaft Width One Seventh", symbol: "⇱" },
      { id: 407, name: "White Arrow Shaft Width One Eighth", symbol: "⇲" },
      { id: 408, name: "White Arrow Shaft Width One Ninth", symbol: "⇴" },
      { id: 409, name: "White Arrow Shaft Width One Tenth", symbol: "⇵" },
      { id: 410, name: "White Arrow Shaft Width Zero", symbol: "⇷" },
      { id: 411, name: "White Arrow Shaft Width One", symbol: "⇸" },
      { id: 412, name: "White Arrow Shaft Width Two", symbol: "⇹" },
      { id: 413, name: "White Arrow Shaft Width Three", symbol: "⇺" },
      { id: 414, name: "Upwards White Arrow", symbol: "⇑" },
      { id: 415, name: "Downwards White Arrow", symbol: "⇓" },
      {
        id: 416,
        name: "Leftwards Harpoon With Barb Up Above Leftwards Harpoon With Barb Down",
        symbol: "⇽",
      },
      {
        id: 417,
        name: "Upwards Harpoon With Barb Left Beside Upwards Harpoon With Barb Right",
        symbol: "⇾",
      },
      {
        id: 418,
        name: "Rightwards Harpoon With Barb Up Above Rightwards Harpoon With Barb Down",
        symbol: "⇿",
      },
      { id: 419, name: "Leftwards Arrow To Black Diamond", symbol: "⬳" },
      {
        id: 420,
        name: "Rightwards Arrow From Bar To Black Diamond",
        symbol: "⟿",
      },
      {
        id: 421,
        name: "Upwards Two-Headed Arrow From Small Circle",
        symbol: "⤉",
      },
      {
        id: 422,
        name: "Downwards Two-Headed Arrow From Small Circle",
        symbol: "⤈",
      },
      {
        id: 423,
        name: "Leftwards Double Arrow With Vertical Stroke",
        symbol: "⇻",
      },
      {
        id: 424,
        name: "Rightwards Double Arrow With Vertical Stroke",
        symbol: "⇼",
      },
      {
        id: 425,
        name: "Left Right Double Arrow With Vertical Stroke",
        symbol: "⬴",
      },
      {
        id: 426,
        name: "Rightwards Two-Headed Arrow With Vertical Stroke",
        symbol: "⤀",
      },
      { id: 427, name: "Leftwards Double Arrow", symbol: "⬵" },
      { id: 428, name: "Rightwards Double Arrow", symbol: "⤁" },
      { id: 429, name: "Leftwards Triple Arrow", symbol: "⬹" },
      { id: 430, name: "Rightwards Triple Arrow", symbol: "⤔" },
      { id: 431, name: "Leftwards Squiggle Arrow", symbol: "⬺" },
      { id: 432, name: "Rightwards Squiggle Arrow", symbol: "⤕" },
      { id: 433, name: "Upwards Arrow With Double Stroke", symbol: "⬶" },
      { id: 434, name: "Downwards Arrow With Double Stroke", symbol: "⤅" },
      { id: 435, name: "Leftwards Dashed Arrow", symbol: "⬻" },
      { id: 436, name: "Rightwards Dashed Arrow", symbol: "⤖" },
      { id: 437, name: "Upwards Dashed Arrow", symbol: "⬷" },
      { id: 438, name: "Downwards Dashed Arrow", symbol: "⤐" },
      { id: 439, name: "Leftwards Arrow To Bar", symbol: "⬼" },
      { id: 440, name: "Rightwards Arrow To Bar", symbol: "⤗" },
      { id: 441, name: "Upwards Arrow To Bar", symbol: "⬽" },
      { id: 442, name: "Downwards Arrow To Bar", symbol: "⤘" },
      { id: 443, name: "Rightwards Arrow With Plus Below", symbol: "⤝" },
      { id: 444, name: "Leftwards Arrow With Plus Below", symbol: "⤞" },
      { id: 445, name: "Rightwards Arrow Through X", symbol: "⤟" },
      { id: 446, name: "Left Right Arrow Through Small Circle", symbol: "⤠" },
      {
        id: 447,
        name: "Upwards Two-Headed Arrow From Small Circle",
        symbol: "⤡",
      },
      { id: 448, name: "Left Barb Up Right Barb Down Harpoon", symbol: "⤢" },
      { id: 449, name: "Left Barb Down Right Barb Up Harpoon", symbol: "⤣" },
      { id: 450, name: "Up Barb Right Down Barb Left Harpoon", symbol: "⤤" },
      { id: 451, name: "Up Barb Left Down Barb Right Harpoon", symbol: "⤥" },
      { id: 452, name: "Left Barb Up Right Barb Up Harpoon", symbol: "⤦" },
      { id: 453, name: "Up Barb Right Down Barb Right Harpoon", symbol: "⤪" },
      { id: 454, name: "Left Barb Down Right Barb Down Harpoon", symbol: "⤨" },
      { id: 455, name: "Up Barb Left Down Barb Left Harpoon", symbol: "⤧" },
      { id: 456, name: "Leftwards Harpoon With Barb Up To Bar", symbol: "⤩" },
      { id: 457, name: "Rightwards Harpoon With Barb Up To Bar", symbol: "⤭" },
      { id: 458, name: "Upwards Harpoon With Barb Right To Bar", symbol: "⤮" },
      {
        id: 459,
        name: "Downwards Harpoon With Barb Right To Bar",
        symbol: "⤯",
      },
      { id: 460, name: "Leftwards Harpoon With Barb Down To Bar", symbol: "⤰" },
      {
        id: 461,
        name: "Rightwards Harpoon With Barb Down To Bar",
        symbol: "⤱",
      },
      { id: 462, name: "Upwards Harpoon With Barb Left To Bar", symbol: "⤲" },
      { id: 463, name: "Downwards Harpoon With Barb Left To Bar", symbol: "⤫" },
      { id: 464, name: "Leftwards Harpoon With Barb Up From Bar", symbol: "⤬" },
      {
        id: 465,
        name: "Rightwards Harpoon With Barb Up From Bar",
        symbol: "⬐",
      },
      {
        id: 466,
        name: "Upwards Harpoon With Barb Right From Bar",
        symbol: "⬎",
      },
      {
        id: 467,
        name: "Downwards Harpoon With Barb Right From Bar",
        symbol: "⬑",
      },
      {
        id: 468,
        name: "Leftwards Harpoon With Barb Down From Bar",
        symbol: "⬏",
      },
      {
        id: 469,
        name: "Rightwards Harpoon With Barb Down From Bar",
        symbol: "⤶",
      },
      { id: 470, name: "Upwards Harpoon With Barb Left From Bar", symbol: "⤷" },
      {
        id: 471,
        name: "Downwards Harpoon With Barb Left From Bar",
        symbol: "⥂",
      },
      {
        id: 472,
        name: "Leftwards Harpoon Over Rightwards Harpoon",
        symbol: "⥃",
      },
      {
        id: 473,
        name: "Rightwards Harpoon Over Leftwards Harpoon",
        symbol: "⥄",
      },
      {
        id: 474,
        name: "Leftwards Double Arrow With Triangle Arrowheads",
        symbol: "⭀",
      },
      {
        id: 475,
        name: "Rightwards Double Arrow With Triangle Arrowheads",
        symbol: "⥱",
      },
      {
        id: 476,
        name: "Upwards Double Arrow With Triangle Arrowheads",
        symbol: "⥶",
      },
      {
        id: 477,
        name: "Downwards Double Arrow With Triangle Arrowheads",
        symbol: "⥸",
      },
      { id: 478, name: "Leftwards Arrow To Black Diamond", symbol: "⭂" },
      { id: 479, name: "Rightwards Arrow To Black Diamond", symbol: "⭈" },
      { id: 480, name: "Upwards Arrow To Black Diamond", symbol: "⭊" },
      { id: 481, name: "Downwards Arrow To Black Diamond", symbol: "⥵" },
      {
        id: 482,
        name: "Rightwards Arrow From Bar To Black Diamond",
        symbol: "⭁",
      },
      {
        id: 483,
        name: "Leftwards Arrow From Bar To Black Diamond",
        symbol: "⭇",
      },
      { id: 484, name: "Upwards Arrow From Bar To Black Diamond", symbol: "⭉" },
      {
        id: 485,
        name: "Downwards Arrow From Bar To Black Diamond",
        symbol: "⥲",
      },
      { id: 486, name: "Rightwards Arrow With Dotted Stem", symbol: "⭋" },
      { id: 487, name: "Upwards Arrow With Dotted Stem", symbol: "⭌" },
      { id: 488, name: "Leftwards Arrow With Dotted Stem", symbol: "⥳" },
      { id: 489, name: "Downwards Arrow With Dotted Stem", symbol: "⥴" },
      {
        id: 490,
        name: "Rightwards Arrow With Tail With Vertical Stroke",
        symbol: "⥆",
      },
      {
        id: 491,
        name: "Rightwards Arrow With Tail With Double Vertical Stroke",
        symbol: "⥅",
      },
      { id: 492, name: "Rightwards Double Arrow With Tail", symbol: "⥹" },
      {
        id: 493,
        name: "Rightwards Double Arrow With Tail With Vertical Stroke",
        symbol: "⥻",
      },
      {
        id: 494,
        name: "Rightwards Double Arrow With Tail With Double Vertical Stroke",
        symbol: "⬰",
      },
      {
        id: 495,
        name: "Leftwards Arrow With Tail With Vertical Stroke",
        symbol: "⥈",
      },
      {
        id: 496,
        name: "Leftwards Arrow With Tail With Double Vertical Stroke",
        symbol: "⬾",
      },
      { id: 497, name: "Leftwards Double Arrow With Tail", symbol: "⥇" },
      {
        id: 498,
        name: "Leftwards Double Arrow With Tail With Vertical Stroke",
        symbol: "⬲",
      },
      {
        id: 499,
        name: "Leftwards Double Arrow With Tail With Double Vertical Stroke",
        symbol: "⟴",
      },
      { id: 500, name: "Rightwards Arrow With Loop", symbol: "⥷" },
      { id: 501, name: "Leftwards Arrow With Loop", symbol: "⭃" },
      { id: 502, name: "Rightwards Arrow With Hook", symbol: "⥺" },
      { id: 503, name: "Leftwards Arrow With Hook", symbol: "⭄" },
      {
        id: 504,
        name: "Rightwards Harpoon With Barb Up Above Long Dash",
        symbol: "⥉",
      },
      {
        id: 505,
        name: "Rightwards Harpoon With Barb Down Below Long Dash",
        symbol: "⥰",
      },
      {
        id: 506,
        name: "Leftwards Harpoon With Barb Up Above Long Dash",
        symbol: "⬿",
      },
      {
        id: 507,
        name: "Leftwards Harpoon With Barb Down Below Long Dash",
        symbol: "⤳",
      },
      {
        id: 508,
        name: "Rightwards Harpoon With Barb Up Above Rightwards Harpoon With Barb Down",
        symbol: "⥊",
      },
      {
        id: 509,
        name: "Upwards Harpoon With Barb Left Beside Upwards Harpoon With Barb Right",
        symbol: "⥋",
      },
      {
        id: 510,
        name: "Downwards Harpoon With Barb Left Beside Downwards Harpoon With Barb Right",
        symbol: "⥌",
      },
      {
        id: 511,
        name: "Rightwards Harpoon With Barb Up Above Leftwards Harpoon With Barb Up",
        symbol: "⥍",
      },
      {
        id: 512,
        name: "Rightwards Harpoon With Barb Down Above Leftwards Harpoon With Barb Down",
        symbol: "⥎",
      },
      {
        id: 513,
        name: "Leftwards Harpoon With Barb Up Above Rightwards Harpoon With Barb Up",
        symbol: "⥏",
      },
      {
        id: 514,
        name: "Leftwards Harpoon With Barb Down Above Rightwards Harpoon With Barb Down",
        symbol: "⥐",
      },
      {
        id: 515,
        name: "Leftwards Harpoon With Barb Up Above Long Dash",
        symbol: "⥑",
      },
      {
        id: 516,
        name: "Leftwards Harpoon With Barb Down Above Long Dash",
        symbol: "⥒",
      },
      {
        id: 517,
        name: "Rightwards Harpoon With Barb Up Above Long Dash",
        symbol: "⥓",
      },
      {
        id: 518,
        name: "Rightwards Harpoon With Barb Down Above Long Dash",
        symbol: "⥔",
      },
      {
        id: 519,
        name: "Upwards Harpoon With Barb Left Above Long Dash",
        symbol: "⥕",
      },
      {
        id: 520,
        name: "Upwards Harpoon With Barb Right Above Long Dash",
        symbol: "⥖",
      },
      {
        id: 521,
        name: "Downwards Harpoon With Barb Left Above Long Dash",
        symbol: "⥗",
      },
      {
        id: 522,
        name: "Downwards Harpoon With Barb Right Above Long Dash",
        symbol: "⥘",
      },
      { id: 523, name: "Rightwards Arrow With Dotted Stem", symbol: "⥙" },
      { id: 524, name: "Upwards Arrow With Dotted Stem", symbol: "⥚" },
      { id: 525, name: "Leftwards Arrow With Dotted Stem", symbol: "⥛" },
      { id: 526, name: "Downwards Arrow With Dotted Stem", symbol: "⥜" },
      { id: 527, name: "Rightwards Arrow With Tail", symbol: "⥝" },
      { id: 528, name: "Leftwards Arrow With Tail", symbol: "⥞" },
      { id: 529, name: "Upwards Arrow With Tail", symbol: "⥟" },
      { id: 530, name: "Downwards Arrow With Tail", symbol: "⥠" },
      { id: 531, name: "Rightwards Arrow From Bar", symbol: "⥡" },
      { id: 532, name: "Upwards Arrow From Bar", symbol: "⥢" },
      { id: 533, name: "Leftwards Arrow From Bar", symbol: "⥤" },
      { id: 534, name: "Downwards Arrow From Bar", symbol: "⥣" },
      { id: 535, name: "Upwards Arrow Left Of Downwards Arrow", symbol: "⥥" },
      { id: 536, name: "Rightwards Arrow With Vertical Stroke", symbol: "⥦" },
      { id: 537, name: "Leftwards Arrow With Vertical Stroke", symbol: "⥨" },
      {
        id: 538,
        name: "Rightwards Arrow With Double Vertical Stroke",
        symbol: "⥧",
      },
      {
        id: 539,
        name: "Leftwards Arrow With Double Vertical Stroke",
        symbol: "⥩",
      },
      { id: 540, name: "Left Right Arrow With Vertical Stroke", symbol: "⥮" },
      {
        id: 541,
        name: "Left Right Arrow With Double Vertical Stroke",
        symbol: "⥯",
      },
      { id: 542, name: "Leftwards Open-Headed Arrow", symbol: "⥪" },
      { id: 543, name: "Rightwards Open-Headed Arrow", symbol: "⥬" },
      { id: 544, name: "Left Right Open-Headed Arrow", symbol: "⥫" },
      { id: 545, name: "Up Down Open-Headed Arrow", symbol: "⥭" },
      { id: 547, name: "Leftwards Two-Headed Arrow", symbol: "⥦" },
      { id: 548, name: "Rightwards Two-Headed Arrow", symbol: "⥨" },
      { id: 549, name: "Leftwards Open-Headed Arrow", symbol: "⥧" },
      { id: 550, name: "Rightwards Open-Headed Arrow", symbol: "⥩" },
      { id: 551, name: "Upwards Open-Headed Arrow", symbol: "⥮" },
      { id: 552, name: "Downwards Open-Headed Arrow", symbol: "⥯" },
      { id: 553, name: "Leftwards Rightwards Open-Headed Arrow", symbol: "⥪" },
      { id: 554, name: "Rightwards Leftwards Open-Headed Arrow", symbol: "⥬" },
      { id: 555, name: "Left Right Open-Headed Arrow", symbol: "⥫" },
      { id: 556, name: "Up Down Open-Headed Arrow", symbol: "⥭" },
      { id: 557, name: "Rightwards Squiggle Arrow", symbol: "⤌" },
      { id: 558, name: "Leftwards Squiggle Arrow", symbol: "⤍" },
      {
        id: 559,
        name: "Rightwards Two-Headed Arrow with Vertical Stroke",
        symbol: "⤎",
      },
      {
        id: 560,
        name: "Leftwards Two-Headed Arrow with Vertical Stroke",
        symbol: "⤏",
      },
      { id: 561, name: "Rightwards Harpoon with Barb Upwards", symbol: "⬸" },
      { id: 562, name: "Leftwards Harpoon with Barb Upwards", symbol: "⤑" },
      { id: 563, name: "Rightwards Harpoon with Barb Downwards", symbol: "⬱" },
      { id: 564, name: "Leftwards Harpoon with Barb Downwards", symbol: "⟸" },
      { id: 565, name: "Rightwards Harpoon with Barb Downwards", symbol: "⟹" },
      { id: 566, name: "Leftwards Harpoon with Barb Downwards", symbol: "⟺" },
      { id: 567, name: "Rightwards Double Arrow", symbol: "⤂" },
      { id: 568, name: "Leftwards Double Arrow", symbol: "⤃" },
      { id: 569, name: "Upwards Double Arrow", symbol: "⤄" },
      { id: 570, name: "Downwards Double Arrow", symbol: "⤆" },
      { id: 571, name: "Leftwards Harpoon with Barb Upwards", symbol: "⤇" },
      { id: 572, name: "Rightwards Harpoon with Barb Upwards", symbol: "⤊" },
      { id: 573, name: "Leftwards Harpoon with Barb Downwards", symbol: "⤋" },
      { id: 574, name: "Rightwards Harpoon with Barb Downwards", symbol: "⭅" },
      { id: 575, name: "Leftwards Harpoon with Barb Downwards", symbol: "⭆" },
      { id: 576, name: "Upwards Harpoon with Barb Downwards", symbol: "⟰" },
      { id: 577, name: "Downwards Harpoon with Barb Upwards", symbol: "⟱" },
      { id: 578, name: "Leftwards Rightwards Double Arrow", symbol: "⇐" },
      { id: 579, name: "Rightwards Leftwards Double Arrow", symbol: "⇒" },
      { id: 580, name: "Left Right Double Arrow", symbol: "⇔" },
      { id: 581, name: "Rightwards Circle Arrow", symbol: "⇶" },
      { id: 582, name: "Leftwards Arrow with Hook", symbol: "⟵" },
      { id: 583, name: "Rightwards Arrow with Hook", symbol: "⟶" },
      { id: 584, name: "Leftwards Twin Arrow", symbol: "⟷" },
      { id: 585, name: "Rightwards Double Arrow", symbol: "⬄" },
      { id: 586, name: "Leftwards Double Arrow", symbol: "⬀" },
      { id: 587, name: "Upwards Arrow", symbol: "⬁" },
      { id: 588, name: "Downwards Arrow", symbol: "⬂" },
      { id: 589, name: "Upwards Downwards Arrow", symbol: "⬃" },
      { id: 590, name: "Leftwards Arrow with Hook", symbol: "⬅" },
      { id: 591, name: "Upwards Arrow with Hook", symbol: "⬆" },
      { id: 592, name: "Downwards Arrow with Hook", symbol: "⬇" },
      { id: 593, name: "Leftwards Hook Arrow", symbol: "⬈" },
      { id: 594, name: "Rightwards Hook Arrow", symbol: "⬉" },
      { id: 595, name: "Upwards Hook Arrow", symbol: "⬊" },
      { id: 596, name: "Downwards Hook Arrow", symbol: "⬋" },
      { id: 597, name: "Leftwards Open-Headed Arrow", symbol: "⬌" },
      { id: 598, name: "Rightwards Open-Headed Arrow", symbol: "⬍" },
    ],
  },
  {
    category: "Astrological Zodiac Signs",
    items: [
      { id: 599, name: "Peace Symbol", symbol: "☮" },
      { id: 600, name: "Wheel of Dharma", symbol: "☸" },
      { id: 601, name: "Aries", symbol: "♈" },
      { id: 602, name: "Taurus", symbol: "♉" },
      { id: 603, name: "Star and Crescent", symbol: "☪" },
      { id: 604, name: "Gemini", symbol: "♊" },
      { id: 605, name: "Cancer", symbol: "♋" },
      { id: 606, name: "Leo", symbol: "♌" },
      { id: 607, name: "Virgo", symbol: "♍" },
      { id: 608, name: "Libra", symbol: "♎" },
      { id: 609, name: "Scorpio", symbol: "♏" },
      { id: 610, name: "Sagittarius", symbol: "♐" },
      { id: 611, name: "Capricorn", symbol: "♑" },
      { id: 612, name: "Aquarius", symbol: "♒" },
      { id: 613, name: "Pisces", symbol: "♓" },
      { id: 614, name: "Caduceus", symbol: "☤" },
      { id: 615, name: "Ankh", symbol: "☥" },
      { id: 616, name: "Christian Cross", symbol: "☧" },
      { id: 617, name: "Cross Potent", symbol: "☨" },
      { id: 618, name: "Cross of Lorraine", symbol: "☩" },
      { id: 619, name: "Celtic Cross", symbol: "☫" },
      { id: 620, name: "Iron Cross", symbol: "☬" },
      { id: 621, name: "Hammer and Sickle", symbol: "☭" },
      { id: 622, name: "Yin Yang", symbol: "☯" },
      { id: 623, name: "Moon Crescent", symbol: "☽" },
      { id: 624, name: "Moon Waning", symbol: "☾" },
      { id: 625, name: "Circle Cross", symbol: "✙" },
      { id: 626, name: "Circle Plus", symbol: "✚" },
      { id: 627, name: "Circle Minus", symbol: "✛" },
      { id: 628, name: "Circle Multiplication", symbol: "✜" },
      { id: 629, name: "Christian Cross", symbol: "✝" },
      { id: 630, name: "Star of David", symbol: "✞" },
      { id: 631, name: "Circle with Cross", symbol: "✟" },
      { id: 632, name: "Sun and Moon", symbol: "☯" },
      { id: 633, name: "Ouroboros", symbol: "☽" },
      { id: 634, name: "Celtic Knot", symbol: "✡" },
    ],
  },
  {
    category: "Hearts",
    items: [
      { id: 635, name: "Heart", symbol: "♥" },
      { id: 636, name: "Empty Heart", symbol: "♡" },
      { id: 637, name: "Rotated Heart", symbol: "❥" },
      { id: 638, name: "Heart with Exclamation", symbol: "❣" },
      { id: 639, name: "Heart with Arrow", symbol: "❦" },
      { id: 640, name: "Heart with Ribbon", symbol: "❧" },
      { id: 641, name: "Georgian Letter", symbol: "დ" },
      { id: 642, name: "Georgian Letter", symbol: "ღ" },
      { id: 643, name: "Five Pointed Star", symbol: "۵" },
      { id: 644, name: "Georgian Letter", symbol: "ლ" },
      { id: 645, name: "Bangla Heart", symbol: "ও" },
      { id: 646, name: "Heart with Fire", symbol: "❤️️" },
      { id: 647, name: "Blue Heart", symbol: "💙" },
      { id: 648, name: "Orange Heart", symbol: "🧡" },
      { id: 649, name: "Green Heart", symbol: "💚" },
      { id: 650, name: "Yellow Heart", symbol: "💛" },
      { id: 651, name: "Purple Heart", symbol: "💜" },
      { id: 652, name: "Black Heart", symbol: "🖤" },
      { id: 653, name: "Pink Heart", symbol: "💗" },
      { id: 654, name: "Beating Heart", symbol: "💓" },
      { id: 655, name: "Broken Heart", symbol: "💔" },
      { id: 656, name: "Heart Decoration", symbol: "💟" },
      { id: 657, name: "Sparkling Heart", symbol: "💕" },
      { id: 658, name: "Revolving Heart", symbol: "💖" },
      { id: 659, name: "Heart with Love", symbol: "❣️" },
      { id: 660, name: "Heart with Arrow", symbol: "💘" },
      { id: 661, name: "Heart with Ribbon", symbol: "💝" },
      { id: 662, name: "Heart with Rings", symbol: "💞" },
    ],
  },
  {
    category: "Check Mark Tick",
    items: [
      { id: 663, name: "Check Mark", symbol: "✓" },
      { id: 664, name: "Check Mark with Circle", symbol: "✔" },
      { id: 665, name: "Cross Mark", symbol: "✗" },
      { id: 666, name: "Cross Mark with Slash", symbol: "✘" },
      { id: 667, name: "Cross Mark in Box", symbol: "☓" },
      { id: 668, name: "Logical OR", symbol: "∨" },
      { id: 669, name: "Square Root", symbol: "√" },
      { id: 670, name: "Check Mark Button", symbol: "✔️" },
      { id: 671, name: "Green Check Mark", symbol: "✅" },
      { id: 672, name: "Cross Mark Button", symbol: "❎" },
      { id: 673, name: "Red Cross Mark", symbol: "❌" },
      { id: 674, name: "100 Percent", symbol: "💯" },
      { id: 675, name: "Heavy Check Mark", symbol: "✇" },
      { id: 676, name: "Unchecked Box", symbol: "☐" },
      { id: 677, name: "Checked Box", symbol: "☑" },
      { id: 678, name: "Crossed Box", symbol: "☒" },
      { id: 679, name: "Turned Arrow", symbol: "〤" },
      { id: 680, name: "Checked Box Button", symbol: "〥" },
    ],
  },
  {
    category: "Maths",
    items: [
      { id: 681, name: "Pi", symbol: "π" },
      { id: 682, name: "Infinity", symbol: "∞" },
      { id: 683, name: "Summation", symbol: "Σ" },
      { id: 684, name: "Square Root", symbol: "√" },
      { id: 685, name: "Cube Root", symbol: "∛" },
      { id: 686, name: "Fourth Root", symbol: "∜" },
      { id: 687, name: "Integral", symbol: "∫" },
      { id: 688, name: "Double Integral", symbol: "∬" },
      { id: 689, name: "Triple Integral", symbol: "∭" },
      { id: 690, name: "Contour Integral", symbol: "∮" },
      { id: 691, name: "Surface Integral", symbol: "∯" },
      { id: 692, name: "Volume Integral", symbol: "∰" },
      { id: 693, name: "Clockwise Contour Integral", symbol: "∱" },
      { id: 694, name: "Anticlockwise Contour Integral", symbol: "∲" },
      { id: 695, name: "Contour Integral", symbol: "∳" },
      { id: 696, name: "Universal Quantifier", symbol: "∀" },
      { id: 697, name: "Complement", symbol: "∁" },
      { id: 698, name: "Partial Derivative", symbol: "∂" },
      { id: 699, name: "Existential Quantifier", symbol: "∃" },
      { id: 700, name: "There Does Not Exist", symbol: "∄" },
      { id: 701, name: "Empty Set", symbol: "∅" },
      { id: 702, name: "Increment", symbol: "∆" },
      { id: 703, name: "Nabla", symbol: "∇" },
      { id: 704, name: "Element Of", symbol: "∈" },
      { id: 705, name: "Not Element Of", symbol: "∉" },
      { id: 706, name: "Small Element Of", symbol: "∊" },
      { id: 707, name: "Such That", symbol: "∋" },
      { id: 708, name: "Do Not Belong", symbol: "∌" },
      { id: 709, name: "Small Not Element Of", symbol: "∍" },
      { id: 710, name: "End of Proof", symbol: "∎" },
      { id: 711, name: "Product", symbol: "∏" },
      { id: 712, name: "Coproduct", symbol: "∐" },
      { id: 713, name: "Summation", symbol: "∑" },
      { id: 714, name: "Minus", symbol: "−" },
      { id: 715, name: "Minus-Plus", symbol: "∓" },
      { id: 716, name: "Dot Plus", symbol: "∔" },
      { id: 717, name: "Division Slash", symbol: "∕" },
      { id: 718, name: "Set Minus", symbol: "∖" },
      { id: 719, name: "Star Operator", symbol: "∗" },
      { id: 720, name: "Circled Dot", symbol: "∘" },
      { id: 721, name: "Bullet", symbol: "∙" },
      { id: 722, name: "Proportional To", symbol: "∝" },
      { id: 723, name: "Perpendicular", symbol: "∟" },
      { id: 724, name: "Angle", symbol: "∠" },
      { id: 725, name: "Measured Angle", symbol: "∡" },
      { id: 726, name: "Spherical Angle", symbol: "∢" },
      { id: 727, name: "Divides", symbol: "∣" },
      { id: 728, name: "Does Not Divide", symbol: "∤" },
      { id: 729, name: "Parallel To", symbol: "∥" },
      { id: 730, name: "Not Parallel To", symbol: "∦" },
      { id: 731, name: "Logical AND", symbol: "∧" },
      { id: 732, name: "Logical OR", symbol: "∨" },
      { id: 733, name: "Intersection", symbol: "∩" },
      { id: 734, name: "Union", symbol: "∪" },
      { id: 735, name: "Therefore", symbol: "∴" },
      { id: 736, name: "Because", symbol: "∵" },
      { id: 737, name: "Ratio", symbol: "∶" },
      { id: 738, name: "Proportion", symbol: "∷" },
      { id: 739, name: "Dot Minus", symbol: "∸" },
      { id: 740, name: "Dot Plus", symbol: "∹" },
      { id: 741, name: "Asterisk Operator", symbol: "∺" },
      { id: 742, name: "Tilde Operator", symbol: "∻" },
      { id: 743, name: "Tilde Equal", symbol: "∼" },
      { id: 744, name: "Tilde Similar", symbol: "∽" },
      { id: 745, name: "Reversed Tilde", symbol: "∾" },
      { id: 746, name: "Inverted Tilde", symbol: "∿" },
      { id: 747, name: "General Epsilon", symbol: "≀" },
      { id: 748, name: "Not Equal", symbol: "≁" },
      { id: 749, name: "Approaches", symbol: "≂" },
      { id: 750, name: "Asymptotically Equal", symbol: "≃" },
      { id: 751, name: "Asymptotically Equal", symbol: "≄" },
      { id: 752, name: "Congruent", symbol: "≅" },
      { id: 753, name: "Similar", symbol: "≈" },
      { id: 754, name: "Not Congruent", symbol: "≉" },
      { id: 755, name: "Not Similar", symbol: "≊" },
      { id: 756, name: "Identical To", symbol: "≋" },
      { id: 757, name: "Strictly Identical To", symbol: "≌" },
      { id: 758, name: "Not Identical To", symbol: "≍" },
      { id: 759, name: "Equivalent To", symbol: "≎" },
      { id: 760, name: "Strictly Equivalent To", symbol: "≏" },
      { id: 761, name: "Equal To By Definition", symbol: "≐" },
      { id: 762, name: "Definitional Equality", symbol: "≑" },
      { id: 763, name: "Approximately Equal To", symbol: "≒" },
      { id: 764, name: "Asymptotic Equal", symbol: "≓" },
      { id: 765, name: "Equals Sign", symbol: "≔" },
      { id: 766, name: "Approximation", symbol: "≕" },
      { id: 767, name: "Doubly Equivalent To", symbol: "≖" },
      { id: 768, name: "Triple Equivalent", symbol: "≗" },
      { id: 769, name: "Does Not Equal", symbol: "≘" },
      { id: 770, name: "Not Equivalent To", symbol: "≙" },
      { id: 771, name: "Orthogonal", symbol: "⊥" },
      { id: 772, name: "For All", symbol: "∀" },
      { id: 773, name: "There Exists", symbol: "∃" },
      { id: 774, name: "Not Exists", symbol: "∄" },
      { id: 775, name: "Set Inclusion", symbol: "⊆" },
      { id: 776, name: "Set Exclusion", symbol: "⊈" },
      { id: 777, name: "Subset of", symbol: "⊂" },
      { id: 778, name: "Superset of", symbol: "⊃" },
      { id: 779, name: "Intersection", symbol: "∩" },
      { id: 780, name: "Union", symbol: "∪" },
      { id: 781, name: "Subset Equal To", symbol: "⊆" },
      { id: 782, name: "Superset Equal To", symbol: "⊇" },
      { id: 783, name: "Does Not Belong", symbol: "∌" },
      { id: 784, name: "Belongs To", symbol: "∈" },
      { id: 785, name: "Does Not Belong To", symbol: "∉" },
      { id: 786, name: "Not Equal", symbol: "≠" },
      { id: 787, name: "Less Than", symbol: "≤" },
      { id: 788, name: "Greater Than", symbol: "≥" },
      { id: 789, name: "Less Than or Equal To", symbol: "≦" },
      { id: 790, name: "Greater Than or Equal To", symbol: "≧" },
      { id: 791, name: "Proportional To", symbol: "∝" },
      { id: 792, name: "Divides", symbol: "∣" },
      { id: 793, name: "Does Not Divide", symbol: "∤" },
      { id: 794, name: "Parallel To", symbol: "∥" },
      { id: 795, name: "Not Parallel To", symbol: "∦" },
      { id: 796, name: "Logical AND", symbol: "∧" },
      { id: 797, name: "Logical OR", symbol: "∨" },
      { id: 798, name: "Dot", symbol: "∙" },
      { id: 799, name: "Diamond", symbol: "⋄" },
      { id: 800, name: "Cups and Crosses", symbol: "⋉" },
      { id: 801, name: "Cup", symbol: "⋃" },
      { id: 802, name: "Intersection", symbol: "⋂" },
    ],
  },
  {
    category: "Number",
    items: [
      { id: 803, name: "Roman Numeral I", symbol: "Ⅰ" },
      { id: 804, name: "Roman Numeral II", symbol: "Ⅱ" },
      { id: 805, name: "Roman Numeral III", symbol: "Ⅲ" },
      { id: 806, name: "Roman Numeral IV", symbol: "Ⅳ" },
      { id: 807, name: "Roman Numeral V", symbol: "Ⅴ" },
      { id: 808, name: "Roman Numeral VI", symbol: "Ⅵ" },
      { id: 809, name: "Roman Numeral VII", symbol: "Ⅶ" },
      { id: 810, name: "Roman Numeral VIII", symbol: "Ⅷ" },
      { id: 811, name: "Roman Numeral IX", symbol: "Ⅸ" },
      { id: 812, name: "Roman Numeral X", symbol: "Ⅹ" },
      { id: 813, name: "Roman Numeral XI", symbol: "Ⅺ" },
      { id: 814, name: "Roman Numeral XII", symbol: "Ⅻ" },
      { id: 815, name: "Roman Numeral L", symbol: "Ⅼ" },
      { id: 816, name: "Roman Numeral C", symbol: "Ⅽ" },
      { id: 817, name: "Roman Numeral D", symbol: "Ⅾ" },
      { id: 818, name: "Roman Numeral M", symbol: "Ⅿ" },
      { id: 819, name: "Roman Numeral i", symbol: "ⅰ" },
      { id: 820, name: "Roman Numeral ii", symbol: "ⅱ" },
      { id: 821, name: "Roman Numeral iii", symbol: "ⅲ" },
      { id: 822, name: "Roman Numeral iv", symbol: "ⅳ" },
      { id: 823, name: "Roman Numeral v", symbol: "ⅴ" },
      { id: 824, name: "Roman Numeral vi", symbol: "ⅵ" },
      { id: 825, name: "Roman Numeral vii", symbol: "ⅶ" },
      { id: 826, name: "Roman Numeral viii", symbol: "ⅷ" },
      { id: 827, name: "Roman Numeral ix", symbol: "ⅸ" },
      { id: 828, name: "Roman Numeral x", symbol: "ⅹ" },
      { id: 829, name: "Roman Numeral xi", symbol: "ⅺ" },
      { id: 830, name: "Roman Numeral xii", symbol: "ⅻ" },
      { id: 831, name: "Roman Numeral l", symbol: "ⅼ" },
      { id: 832, name: "Roman Numeral c", symbol: "ⅽ" },
      { id: 833, name: "Roman Numeral d", symbol: "ⅾ" },
      { id: 834, name: "Roman Numeral m", symbol: "ⅿ" },
      { id: 835, name: "Roman Numeral ↀ", symbol: "ↀ" },
      { id: 836, name: "Roman Numeral ↁ", symbol: "ↁ" },
      { id: 837, name: "Roman Numeral ↂ", symbol: "ↂ" },
      { id: 838, name: "Number ➀", symbol: "➀" },
      { id: 839, name: "Number ➁", symbol: "➁" },
      { id: 840, name: "Number ➂", symbol: "➂" },
      { id: 841, name: "Number ➃", symbol: "➃" },
      { id: 842, name: "Number ➄", symbol: "➄" },
      { id: 843, name: "Number ➅", symbol: "➅" },
      { id: 844, name: "Number ➆", symbol: "➆" },
      { id: 845, name: "Number ➇", symbol: "➇" },
      { id: 846, name: "Number ➈", symbol: "➈" },
      { id: 847, name: "Number ➉", symbol: "➉" },
      { id: 848, name: "Number ➊", symbol: "➊" },
      { id: 849, name: "Number ➋", symbol: "➋" },
      { id: 850, name: "Number ➌", symbol: "➌" },
      { id: 851, name: "Number ➍", symbol: "➍" },
      { id: 852, name: "Number ➎", symbol: "➎" },
      { id: 853, name: "Number ➏", symbol: "➏" },
      { id: 854, name: "Number ➐", symbol: "➐" },
      { id: 855, name: "Number ➑", symbol: "➑" },
      { id: 856, name: "Number ➒", symbol: "➒" },
      { id: 857, name: "Number ➓", symbol: "➓" },
      { id: 858, name: "Number ⓵", symbol: "⓵" },
      { id: 859, name: "Number ⓶", symbol: "⓶" },
      { id: 860, name: "Number ⓷", symbol: "⓷" },
      { id: 861, name: "Number ⓸", symbol: "⓸" },
      { id: 862, name: "Number ⓹", symbol: "⓹" },
      { id: 863, name: "Number ⓺", symbol: "⓺" },
      { id: 864, name: "Number ⓻", symbol: "⓻" },
      { id: 865, name: "Number ⓼", symbol: "⓼" },
      { id: 866, name: "Number ⓽", symbol: "⓽" },
      { id: 867, name: "Number ⓾", symbol: "⓾" },
      { id: 868, name: "Number ⓿", symbol: "⓿" },
      { id: 869, name: "Number ❶", symbol: "❶" },
      { id: 870, name: "Number ❷", symbol: "❷" },
      { id: 871, name: "Number ❸", symbol: "❸" },
      { id: 872, name: "Number ❹", symbol: "❹" },
      { id: 873, name: "Number ❺", symbol: "❺" },
      { id: 874, name: "Number ❻", symbol: "❻" },
      { id: 875, name: "Number ❼", symbol: "❼" },
      { id: 876, name: "Number ❽", symbol: "❽" },
      { id: 877, name: "Number ❾", symbol: "❾" },
      { id: 878, name: "Number ❿", symbol: "❿" },
    ],
  },
  {
    category: "Fraction",
    items: [
      { id: 879, name: "Fraction One Half", symbol: "½" },
      { id: 880, name: "Fraction One Third", symbol: "⅓" },
      { id: 881, name: "Fraction One Fifth", symbol: "⅕" },
      { id: 882, name: "Fraction One Sixth", symbol: "⅙" },
      { id: 883, name: "Fraction One Eighth", symbol: "⅛" },
      { id: 884, name: "Fraction Two Thirds", symbol: "⅔" },
      { id: 885, name: "Fraction Two Fifths", symbol: "⅖" },
      { id: 886, name: "Fraction Five Sixth", symbol: "⅚" },
      { id: 887, name: "Fraction Three Eighths", symbol: "⅜" },
      { id: 888, name: "Fraction Three Quarters", symbol: "¾" },
      { id: 889, name: "Fraction Three Fifths", symbol: "⅗" },
      { id: 890, name: "Fraction Five Eighths", symbol: "⅝" },
      { id: 891, name: "Fraction Seven Eighths", symbol: "⅞" },
      { id: 892, name: "Fraction Four Fifths", symbol: "⅘" },
      { id: 893, name: "Fraction One Quarter", symbol: "¼" },
      { id: 894, name: "Fraction One Seventh", symbol: "⅐" },
      { id: 895, name: "Fraction One Ninth", symbol: "⅑" },
      { id: 896, name: "Fraction One Tenth", symbol: "⅒" },
      { id: 897, name: "Per Thousand", symbol: "‰" },
      { id: 898, name: "Per Ten Thousand", symbol: "‱" },
      { id: 899, name: "Percentage", symbol: "%" },
      { id: 900, name: "Cent Sign", symbol: "℅" },
    ],
  },
  {
    category: "Comparison",
    items: [
      { id: 901, name: "Less Than or Equal", symbol: "≤" },
      { id: 902, name: "Greater Than or Equal", symbol: "≥" },
      { id: 903, name: "Less Than or Equal To", symbol: "≦" },
      { id: 904, name: "Greater Than or Equal To", symbol: "≧" },
      { id: 905, name: "Precedes", symbol: "≨" },
      { id: 906, name: "Succeeds", symbol: "≩" },
      { id: 907, name: "Left Parenthesis", symbol: "⊰" },
      { id: 908, name: "Right Parenthesis", symbol: "⊱" },
      { id: 909, name: "Subset Not Equal", symbol: "⋛" },
      { id: 910, name: "Superset Not Equal", symbol: "⋚" },
      { id: 911, name: "Asymptotically Equal", symbol: "≂" },
      { id: 912, name: "Approximately Equal", symbol: "≃" },
      { id: 913, name: "Not Equal to", symbol: "≄" },
      { id: 914, name: "Congruent", symbol: "≅" },
      { id: 915, name: "Similar to", symbol: "≆" },
      { id: 916, name: "Not Similar to", symbol: "≇" },
      { id: 917, name: "Approximately", symbol: "≈" },
      { id: 918, name: "Not Approximately", symbol: "≉" },
      { id: 919, name: "Inclusion", symbol: "≊" },
      { id: 920, name: "Not Inclusion", symbol: "≋" },
      { id: 921, name: "Exact Same", symbol: "≌" },
      { id: 922, name: "Not Exact Same", symbol: "≍" },
      { id: 923, name: "Equivalent", symbol: "≎" },
      { id: 924, name: "Not Equivalent", symbol: "≏" },
      { id: 925, name: "Equal to", symbol: "≐" },
      { id: 926, name: "Not Equal to", symbol: "≑" },
      { id: 927, name: "Almost Equal", symbol: "≒" },
      { id: 928, name: "Not Almost Equal", symbol: "≓" },
      { id: 929, name: "Equal to with Approximation", symbol: "≔" },
      { id: 930, name: "Not Equal to with Approximation", symbol: "≕" },
      { id: 931, name: "Identical to", symbol: "≖" },
      { id: 932, name: "Not Identical to", symbol: "≗" },
      { id: 933, name: "Not Identical", symbol: "≘" },
      { id: 934, name: "Not Identical to", symbol: "≙" },
      { id: 935, name: "Precedes", symbol: "≚" },
      { id: 936, name: "Succeeds", symbol: "≛" },
      { id: 937, name: "Not Equal", symbol: "≜" },
      { id: 938, name: "Equivalent", symbol: "≝" },
      { id: 939, name: "Equal", symbol: "≞" },
      { id: 940, name: "Not Equal", symbol: "≟" },
      { id: 941, name: "Does Not Equal", symbol: "≠" },
      { id: 942, name: "Equivalent to", symbol: "≡" },
      { id: 943, name: "Not Equivalent", symbol: "≢" },
      { id: 944, name: "Identical to", symbol: "≣" },
    ],
  },
  {
    category: "Technical",
    items: [
      { id: 945, name: "Diameter", symbol: "⌀" },
      { id: 946, name: "House", symbol: "⌂" },
      { id: 947, name: "Up Arrowhead", symbol: "⌃" },
      { id: 948, name: "Down Arrowhead", symbol: "⌄" },
      { id: 949, name: "Projective", symbol: "⌅" },
      { id: 950, name: "Perspective", symbol: "⌆" },
      { id: 951, name: "Wavy Line", symbol: "⌇" },
      { id: 952, name: "Left Ceiling", symbol: "⌈" },
      { id: 953, name: "Right Ceiling", symbol: "⌉" },
      { id: 954, name: "Left Floor", symbol: "⌊" },
      { id: 955, name: "Right Floor", symbol: "⌋" },
      { id: 956, name: "Bottom Left Crop", symbol: "⌌" },
      { id: 957, name: "Bottom Right Crop", symbol: "⌍" },
      { id: 958, name: "Top Right Crop", symbol: "⌎" },
      { id: 959, name: "Top Left Crop", symbol: "⌏" },
      { id: 960, name: "Reversed Not Sign", symbol: "⌐" },
      { id: 961, name: "Square Lozenge", symbol: "⌑" },
      { id: 962, name: "Arc", symbol: "⌒" },
      { id: 963, name: "Segment", symbol: "⌓" },
      { id: 964, name: "Sector", symbol: "⌔" },
      { id: 965, name: "Telephone Recorder", symbol: "⌕" },
      { id: 966, name: "Position Indicator", symbol: "⌖" },
      { id: 967, name: "Viewdata Square", symbol: "⌗" },
      { id: 968, name: "Place of Interest Sign", symbol: "⌘" },
      { id: 969, name: "Turned Not Sign", symbol: "⌙" },
      { id: 970, name: "Watch", symbol: "⌚" },
      { id: 971, name: "Hourglass", symbol: "⌛" },
      { id: 972, name: "Top Left Corner", symbol: "⌜" },
      { id: 973, name: "Top Right Corner", symbol: "⌝" },
      { id: 974, name: "Bottom Left Corner", symbol: "⌞" },
      { id: 975, name: "Bottom Right Corner", symbol: "⌟" },
      { id: 976, name: "Top Half Integral", symbol: "⌠" },
      { id: 977, name: "Bottom Half Integral", symbol: "⌡" },
      { id: 978, name: "Frown", symbol: "⌢" },
      { id: 979, name: "Smile", symbol: "⌣" },
      {
        id: 980,
        name: "Up Arrowhead Between Two Horizontal Bars",
        symbol: "⌤",
      },
      { id: 981, name: "Option Key", symbol: "⌥" },
      { id: 982, name: "Erase to the Right", symbol: "⌦" },
      { id: 983, name: "X in a Rectangle Box", symbol: "⌧" },
      { id: 984, name: "Keyboard", symbol: "⌨" },
      { id: 985, name: "Erase to the Left", symbol: "⌫" },
      { id: 986, name: "Benzene Ring", symbol: "⌬" },
      { id: 987, name: "Cylindricity", symbol: "⌭" },
      { id: 988, name: "All Around Profile", symbol: "⌮" },
      { id: 989, name: "Symmetry", symbol: "⌯" },
      { id: 990, name: "Total Runout", symbol: "⌰" },
      { id: 991, name: "Dimension Origin", symbol: "⌱" },
      { id: 992, name: "Conical Taper", symbol: "⌲" },
      { id: 993, name: "Slope", symbol: "⌳" },
      { id: 994, name: "Counterbore", symbol: "⌴" },
      { id: 995, name: "Countersink", symbol: "⌵" },
      { id: 996, name: "APL Functional Symbol I-Beam", symbol: "⌶" },
      { id: 997, name: "APL Functional Symbol Squish Quad", symbol: "⌷" },
      { id: 998, name: "APL Functional Symbol Quad Equal", symbol: "⌸" },
      { id: 999, name: "APL Functional Symbol Quad Divide", symbol: "⌹" },
      { id: 1000, name: "APL Functional Symbol Quad Diamond", symbol: "⌺" },
      { id: 1001, name: "APL Functional Symbol Quad Jersey", symbol: "⌻" },
      { id: 1002, name: "APL Functional Symbol Quad Circle", symbol: "⌼" },
      { id: 1003, name: "APL Functional Symbol Circle Stile", symbol: "⌽" },
      { id: 1004, name: "APL Functional Symbol Circle Jot", symbol: "⌾" },
      { id: 1005, name: "APL Functional Symbol Slash Bar", symbol: "⌿" },
      { id: 1006, name: "APL Functional Symbol Backslash Bar", symbol: "⍀" },
      { id: 1007, name: "APL Functional Symbol Quad Slash", symbol: "⍁" },
      { id: 1008, name: "APL Functional Symbol Quad Backslash", symbol: "⍂" },
      { id: 1009, name: "APL Functional Symbol Quad Less-Than", symbol: "⍃" },
      {
        id: 1010,
        name: "APL Functional Symbol Quad Greater-Than",
        symbol: "⍄",
      },
      { id: 1011, name: "APL Functional Symbol Leftwards Vane", symbol: "⍅" },
      { id: 1012, name: "APL Functional Symbol Rightwards Vane", symbol: "⍆" },
      {
        id: 1013,
        name: "APL Functional Symbol Quad Leftwards Arrow",
        symbol: "⍇",
      },
      {
        id: 1014,
        name: "APL Functional Symbol Quad Rightwards Arrow",
        symbol: "⍈",
      },
      { id: 1015, name: "APL Functional Symbol Circle Backslash", symbol: "⍉" },
      {
        id: 1016,
        name: "APL Functional Symbol Down Tack Underbar",
        symbol: "⍊",
      },
      { id: 1017, name: "APL Functional Symbol Delta Stile", symbol: "⍋" },
      { id: 1018, name: "APL Functional Symbol Quad Down Caret", symbol: "⍌" },
      { id: 1019, name: "APL Functional Symbol Quad Delta", symbol: "⍍" },
      { id: 1020, name: "APL Functional Symbol Down Tack Jot", symbol: "⍎" },
      { id: 1021, name: "APL Functional Symbol Upwards Vane", symbol: "⍏" },
      {
        id: 1022,
        name: "APL Functional Symbol Quad Upwards Arrow",
        symbol: "⍐",
      },
      { id: 1023, name: "APL Functional Symbol Up Tack Overbar", symbol: "⍑" },
      { id: 1024, name: "APL Functional Symbol Del Stile", symbol: "⍒" },
      { id: 1025, name: "APL Functional Symbol Quad Up Caret", symbol: "⍓" },
      { id: 1026, name: "APL Functional Symbol Quad Del", symbol: "⍔" },
      { id: 1027, name: "APL Functional Symbol Up Tack Jot", symbol: "⍕" },
      { id: 1028, name: "APL Functional Symbol Downwards Vane", symbol: "⍖" },
      {
        id: 1029,
        name: "APL Functional Symbol Quad Downwards Arrow",
        symbol: "⍗",
      },
      { id: 1030, name: "APL Functional Symbol Quote Underbar", symbol: "⍘" },
      { id: 1031, name: "APL Functional Symbol Delta Underbar", symbol: "⍙" },
      { id: 1032, name: "APL Functional Symbol Diamond Underbar", symbol: "⍚" },
      { id: 1033, name: "APL Functional Symbol Jot Underbar", symbol: "⍛" },
      { id: 1034, name: "APL Functional Symbol Circle Underbar", symbol: "⍜" },
      { id: 1035, name: "APL Functional Symbol Up Shoe Jot", symbol: "⍝" },
      { id: 1036, name: "APL Functional Symbol Quote Quad", symbol: "⍞" },
      { id: 1037, name: "APL Functional Symbol Circle Star", symbol: "⍟" },
      { id: 1038, name: "APL Functional Symbol Quad Colon", symbol: "⍠" },
      {
        id: 1039,
        name: "APL Functional Symbol Up Tack Diaeresis",
        symbol: "⍡",
      },
      { id: 1040, name: "APL Functional Symbol Del Diaeresis", symbol: "⍢" },
      { id: 1041, name: "APL Functional Symbol Star Diaeresis", symbol: "⍣" },
      { id: 1042, name: "APL Functional Symbol Jot Diaeresis", symbol: "⍤" },
      { id: 1043, name: "APL Functional Symbol Circle Diaeresis", symbol: "⍥" },
      { id: 1044, name: "APL Functional Symbol Down Shoe Stile", symbol: "⍦" },
      { id: 1045, name: "APL Functional Symbol Left Shoe Stile", symbol: "⍧" },
      { id: 1046, name: "APL Functional Symbol Tilde Diaeresis", symbol: "⍨" },
      {
        id: 1047,
        name: "APL Functional Symbol Greater-Than Diaeresis",
        symbol: "⍩",
      },
      { id: 1048, name: "APL Functional Symbol Comma Bar", symbol: "⍪" },
      { id: 1049, name: "APL Functional Symbol Del Tilde", symbol: "⍫" },
      { id: 1050, name: "APL Functional Symbol Zilde", symbol: "⍬" },
      { id: 1051, name: "APL Functional Symbol Stile Tilde", symbol: "⍭" },
      {
        id: 1052,
        name: "APL Functional Symbol Semicolon Underbar",
        symbol: "⍮",
      },
      { id: 1053, name: "APL Functional Symbol Quad Not Equal", symbol: "⍯" },
      { id: 1054, name: "APL Functional Symbol Quad Question", symbol: "⍰" },
      { id: 1055, name: "APL Functional Symbol Down Caret Tilde", symbol: "⍱" },
      { id: 1056, name: "APL Functional Symbol Up Caret Tilde", symbol: "⍲" },
      { id: 1057, name: "APL Functional Symbol Iota", symbol: "⍳" },
      { id: 1058, name: "APL Functional Symbol Rho", symbol: "⍴" },
      { id: 1059, name: "APL Functional Symbol Omega", symbol: "⍵" },
      { id: 1060, name: "APL Functional Symbol Alpha Underbar", symbol: "⍶" },
      { id: 1061, name: "APL Functional Symbol Epsilon Underbar", symbol: "⍷" },
      {
        id: 1062,
        name: "APL Functional Symbol Left Tack Underbar",
        symbol: "⍸",
      },
      {
        id: 1063,
        name: "APL Functional Symbol Right Tack Underbar",
        symbol: "⍹",
      },
      { id: 1064, name: "APL Functional Symbol Alpha", symbol: "⍺" },
      { id: 1065, name: "Small Em Dash", symbol: "﹘" },
      { id: 1066, name: "Small Left Curly Bracket", symbol: "﹝" },
      { id: 1067, name: "Small Right Curly Bracket", symbol: "﹞" },
      { id: 1068, name: "Small Number Sign", symbol: "﹟" },
      { id: 1069, name: "Small Asterisk", symbol: "﹡" },
      {
        id: 1070,
        name: "Chinese Symbol for Ideographic Telegraph Line Feed Separator",
        symbol: "〶",
      },
      { id: 1071, name: "Escape", symbol: "␛" },
      { id: 1072, name: "Delete", symbol: "␡" },
      { id: 1073, name: "End of Transmission Block", symbol: "␚" },
      { id: 1074, name: "File Separator", symbol: "␟" },
      { id: 1075, name: "Cancel Character", symbol: "␘" },
      { id: 1076, name: "Space", symbol: "␠" },
      { id: 1077, name: "Line Feed", symbol: "␤" },
      { id: 1078, name: "Form Feed", symbol: "␋" },
      { id: 1079, name: "Carriage Return", symbol: "␌" },
      { id: 1080, name: "Shift Out", symbol: "␍" },
      { id: 1081, name: "Shift In", symbol: "␎" },
      { id: 1082, name: "Data Link Escape", symbol: "␏" },
      { id: 1083, name: "Device Control One", symbol: "␐" },
      { id: 1084, name: "Device Control Two", symbol: "␑" },
      { id: 1085, name: "Device Control Three", symbol: "␒" },
      { id: 1086, name: "Device Control Four", symbol: "␓" },
      { id: 1087, name: "Negative Acknowledge", symbol: "␔" },
      { id: 1088, name: "Synchronous Idle", symbol: "␕" },
      { id: 1089, name: "End of Transmission Block", symbol: "␖" },
      { id: 1090, name: "Cancel", symbol: "␗" },
      { id: 1091, name: "End of Medium", symbol: "␙" },
      { id: 1092, name: "End of Transmission", symbol: "␜" },
      { id: 1093, name: "File Separator", symbol: "␝" },
      { id: 1094, name: "Group Separator", symbol: "␞" },
      { id: 1095, name: "Null", symbol: "␀" },
      { id: 1096, name: "Start of Heading", symbol: "␁" },
      { id: 1097, name: "Start of Text", symbol: "␂" },
      { id: 1098, name: "End of Text", symbol: "␃" },
      { id: 1099, name: "End of Transmission", symbol: "␄" },
      { id: 1100, name: "Enquiry", symbol: "␅" },
      { id: 1101, name: "Acknowledge", symbol: "␆" },
      { id: 1102, name: "Bell", symbol: "␇" },
      { id: 1103, name: "Backspace", symbol: "␈" },
      { id: 1104, name: "Horizontal Tabulation", symbol: "␉" },
      { id: 1105, name: "Line Feed", symbol: "␊" },
      { id: 1106, name: "Vertical Tabulation", symbol: "␋" },
      { id: 1107, name: "Form Feed", symbol: "␌" },
      { id: 1108, name: "Carriage Return", symbol: "␍" },
      { id: 1109, name: "Shift Out", symbol: "␎" },
      { id: 1110, name: "Shift In", symbol: "␏" },
      { id: 1111, name: "Data Link Escape", symbol: "␐" },
      { id: 1112, name: "Device Control One", symbol: "␑" },
      { id: 1113, name: "Device Control Two", symbol: "␒" },
      { id: 1114, name: "Device Control Three", symbol: "␓" },
      { id: 1115, name: "Device Control Four", symbol: "␔" },
      { id: 1116, name: "Negative Acknowledge", symbol: "␕" },
      { id: 1117, name: "Synchronous Idle", symbol: "␖" },
      { id: 1118, name: "End of Transmission Block", symbol: "␗" },
      { id: 1119, name: "Cancel", symbol: "␘" },
      { id: 1120, name: "End of Medium", symbol: "␙" },
      { id: 1121, name: "Substitute", symbol: "␚" },
      { id: 1122, name: "Escape", symbol: "␛" },
      { id: 1123, name: "File Separator", symbol: "␜" },
      { id: 1124, name: "Group Separator", symbol: "␝" },
      { id: 1125, name: "Record Separator", symbol: "␞" },
      { id: 1126, name: "Unit Separator", symbol: "␟" },
      { id: 1127, name: "Blank Symbol", symbol: "␠" },
      { id: 1128, name: "Escape", symbol: "⎋" },
      { id: 1129, name: "Apple Logo", symbol: "" },
      { id: 1130, name: "HD Symbol", symbol: "ᴴᴰ" },
    ],
  },

  {
    category: "Square Rectangle",
    items: [
      { id: 1131, name: "Lower Right Drop-Shadowed Square", symbol: "❏" },
      { id: 1132, name: "Upper Right Drop-Shadowed Square", symbol: "❐" },
      { id: 1133, name: "Lower Right Shadowed Square", symbol: "❑" },
      { id: 1134, name: "Upper Right Shadowed Square", symbol: "❒" },
      { id: 1135, name: "Upper Half Block", symbol: "▀" },
      { id: 1136, name: "Lower One Eighth Block", symbol: "▁" },
      { id: 1137, name: "Lower One Quarter Block", symbol: "▂" },
      { id: 1138, name: "Lower Three Eighths Block", symbol: "▃" },
      { id: 1139, name: "Lower Half Block", symbol: "▄" },
      { id: 1140, name: "Lower Five Eighths Block", symbol: "▅" },
      { id: 1141, name: "Lower Three Quarters Block", symbol: "▆" },
      { id: 1142, name: "Lower Seven Eighths Block", symbol: "▇" },
      { id: 1143, name: "Full Block", symbol: "█" },
      { id: 1144, name: "Left Seven Eighths Block", symbol: "▉" },
      { id: 1145, name: "Left Three Quarters Block", symbol: "▊" },
      { id: 1146, name: "Left Five Eighths Block", symbol: "▋" },
      { id: 1147, name: "Left Half Block", symbol: "▌" },
      { id: 1148, name: "Left Three Eighths Block", symbol: "▍" },
      { id: 1149, name: "Left One Quarter Block", symbol: "▎" },
      { id: 1150, name: "Left One Eighth Block", symbol: "▏" },
      { id: 1151, name: "Right Half Block", symbol: "▐" },
      { id: 1152, name: "Light Shade", symbol: "░" },
      { id: 1153, name: "Medium Shade", symbol: "▒" },
      { id: 1154, name: "Dark Shade", symbol: "▓" },
      { id: 1155, name: "Upper One Eighth Block", symbol: "▔" },
      { id: 1156, name: "Horizontal Rectangle", symbol: "▬" },
      { id: 1157, name: "Square with Diagonal Crosshatch Fill", symbol: "▢" },
      { id: 1158, name: "Square with Checkerboard Fill", symbol: "▣" },
      { id: 1159, name: "Square with Horizontal Fill", symbol: "▤" },
      { id: 1160, name: "Square with Vertical Fill", symbol: "▥" },
      { id: 1161, name: "Square with Orthogonal Crosshatch Fill", symbol: "▦" },
      {
        id: 1162,
        name: "Square with Upper Left to Lower Right Fill",
        symbol: "▧",
      },
      {
        id: 1163,
        name: "Square with Upper Right to Lower Left Fill",
        symbol: "▨",
      },
      { id: 1164, name: "Square with Diagonal Crosshatch Fill", symbol: "▩" },
      { id: 1165, name: "Black Small Square", symbol: "▪" },
      { id: 1166, name: "White Small Square", symbol: "▫" },
      { id: 1167, name: "White Rectangle", symbol: "▭" },
      { id: 1168, name: "Black Vertical Rectangle", symbol: "▮" },
      { id: 1169, name: "White Vertical Rectangle", symbol: "▯" },
      { id: 1170, name: "Trigram for Heaven", symbol: "☰" },
      { id: 1171, name: "Trigram for Fire", symbol: "☲" },
      { id: 1172, name: "Trigram for Lake", symbol: "☱" },
      { id: 1173, name: "Trigram for Wind", symbol: "☴" },
      { id: 1174, name: "Trigram for Water", symbol: "☵" },
      { id: 1175, name: "Trigram for Mountain", symbol: "☶" },
      { id: 1176, name: "Trigram for Thunder", symbol: "☳" },
      { id: 1177, name: "Trigram for Earth", symbol: "☷" },
      { id: 1178, name: "Black Parallelogram", symbol: "▰" },
      { id: 1179, name: "White Parallelogram", symbol: "▱" },
      { id: 1180, name: "Left Half Black Circle", symbol: "◧" },
      { id: 1181, name: "Right Half Black Circle", symbol: "◨" },
      { id: 1182, name: "Top Half Black Circle", symbol: "◩" },
      { id: 1183, name: "Bottom Half Black Circle", symbol: "◪" },
      { id: 1184, name: "Square with Left Half Black", symbol: "◫" },
      { id: 1185, name: "White Vertical Rectangle", symbol: "∎" },
      { id: 1186, name: "Black Square", symbol: "■" },
      { id: 1187, name: "White Square", symbol: "□" },
      { id: 1188, name: "Squared Plus", symbol: "⊞" },
      { id: 1189, name: "Squared Minus", symbol: "⊟" },
      { id: 1190, name: "Squared Times", symbol: "⊠" },
      { id: 1191, name: "Squared Dot Operator", symbol: "⊡" },
      { id: 1192, name: "Light Vertical Bar", symbol: "❘" },
      { id: 1193, name: "Medium Vertical Bar", symbol: "❙" },
      { id: 1194, name: "Heavy Vertical Bar", symbol: "❚" },
      { id: 1195, name: "Geta Mark", symbol: "〓" },
      { id: 1196, name: "Lozenge", symbol: "◊" },
      {
        id: 1197,
        name: "White Diamond Containing Black Small Diamond",
        symbol: "◈",
      },
      { id: 1198, name: "White Diamond", symbol: "◇" },
      { id: 1199, name: "Black Diamond", symbol: "◆" },
      { id: 1200, name: "Square with Vertical Fill", symbol: "⎔" },
      { id: 1201, name: "White Diamond with Centred Dot", symbol: "⎚" },
      { id: 1202, name: "White Shogi Piece", symbol: "☖" },
      { id: 1203, name: "Black Shogi Piece", symbol: "☗" },
    ],
  },
  {
    category: "Triangle",
    items: [
      { id: 1204, name: "Black Left-Pointing Pointer", symbol: "◄" },
      { id: 1205, name: "Black Up-Pointing Triangle", symbol: "▲" },
      { id: 1206, name: "Black Down-Pointing Triangle", symbol: "▼" },
      { id: 1207, name: "Black Right-Pointing Pointer", symbol: "►" },
      { id: 1208, name: "Black Left-Pointing Pointer", symbol: "◀" },
      { id: 1209, name: "Black Lower Left Triangle", symbol: "◣" },
      { id: 1210, name: "Black Lower Right Triangle", symbol: "◥" },
      { id: 1211, name: "Black Upper Left Triangle", symbol: "◤" },
      { id: 1212, name: "Black Upper Right Triangle", symbol: "◢" },
      { id: 1213, name: "Black Right-Pointing Pointer", symbol: "▶" },
      { id: 1214, name: "White Left-Pointing Pointer", symbol: "◂" },
      { id: 1215, name: "Black Up-Pointing Small Triangle", symbol: "▴" },
      { id: 1216, name: "Black Down-Pointing Small Triangle", symbol: "▾" },
      { id: 1217, name: "Black Right-Pointing Small Triangle", symbol: "▸" },
      { id: 1218, name: "White Left-Pointing Small Triangle", symbol: "◁" },
      { id: 1219, name: "White Up-Pointing Triangle", symbol: "△" },
      { id: 1220, name: "White Down-Pointing Triangle", symbol: "▽" },
      { id: 1221, name: "White Right-Pointing Triangle", symbol: "▷" },
      { id: 1222, name: "Increment", symbol: "∆" },
      { id: 1223, name: "Nabla", symbol: "∇" },
      { id: 1224, name: "Right-Pointing Triangle", symbol: "⊳" },
      { id: 1225, name: "Left-Pointing Triangle", symbol: "⊲" },
      { id: 1226, name: "Left-Pointing Triangle Underbar", symbol: "⊴" },
      { id: 1227, name: "Right-Pointing Triangle Underbar", symbol: "⊵" },
      { id: 1228, name: "White Left-Pointing Pointer", symbol: "◅" },
      { id: 1229, name: "Black Right-Pointing Small Triangle", symbol: "▻" },
      { id: 1230, name: "White Up-Pointing Small Triangle", symbol: "▵" },
      { id: 1231, name: "White Down-Pointing Small Triangle", symbol: "▿" },
      { id: 1232, name: "White Left-Pointing Small Triangle", symbol: "◃" },
      { id: 1233, name: "White Right-Pointing Small Triangle", symbol: "▹" },
      {
        id: 1234,
        name: "Up-Pointing Triangle with Left Half Black",
        symbol: "◭",
      },
      {
        id: 1235,
        name: "Up-Pointing Triangle with Right Half Black",
        symbol: "◮",
      },
      { id: 1236, name: "Triple Nested Less-Than", symbol: "⫷" },
      { id: 1237, name: "Triple Nested Greater-Than", symbol: "⫸" },
      { id: 1238, name: "Less-Than with Dot", symbol: "⋖" },
      { id: 1239, name: "Greater-Than with Dot", symbol: "⋗" },
      { id: 1240, name: "Not Normal Subgroup Of", symbol: "⋪" },
      { id: 1241, name: "Not Normal Supergroup Of", symbol: "⋫" },
      { id: 1242, name: "Not Normal Subgroup Of or Equal To", symbol: "⋬" },
      { id: 1243, name: "Not Normal Supergroup Of or Equal To", symbol: "⋭" },
      { id: 1244, name: "Right Triangle", symbol: "⊿" },
      { id: 1245, name: "White Up-Pointing Triangle with Dot", symbol: "◬" },
      { id: 1246, name: "Delta Equal To", symbol: "≜" },
      { id: 1247, name: "Triangle with Underbar", symbol: "⑅" },
    ],
  },

  {
    category: "Line",
    items: [
      { id: 1248, name: "Light Vertical Line", symbol: "│" },
      { id: 1249, name: "Heavy Vertical Line", symbol: "┃" },
      {
        id: 1250,
        name: "Light Vertical Line with Horizontal Stroke",
        symbol: "╽",
      },
      {
        id: 1251,
        name: "Heavy Vertical Line with Horizontal Stroke",
        symbol: "╿",
      },
      { id: 1252, name: "Triple Vertical Bar", symbol: "╏" },
      { id: 1253, name: "Double Vertical Line", symbol: "║" },
      { id: 1254, name: "Dashed Vertical Line", symbol: "╎" },
      { id: 1255, name: "Triple Dash Vertical Line", symbol: "┇" },
      {
        id: 1256,
        name: "Presentation Form For Vertical Em Dash",
        symbol: "︱",
      },
      { id: 1257, name: "Dotted Vertical Line", symbol: "┊" },
      {
        id: 1258,
        name: "Presentation Form For Vertical Horizontal Ellipsis",
        symbol: "︳",
      },
      { id: 1259, name: "Heavy Triple Dash Vertical Line", symbol: "┋" },
      { id: 1260, name: "Double Dash Vertical Line", symbol: "┆" },
      { id: 1261, name: "Box Drawings Light Up", symbol: "╵" },
      { id: 1262, name: "Vertical Ideographic Iteration Mark", symbol: "〡" },
      { id: 1263, name: "Vertical Ideographic Iteration Mark", symbol: "〢" },
      { id: 1264, name: "Box Drawings Heavy Up", symbol: "╹" },
      { id: 1265, name: "Box Drawings Heavy Down", symbol: "╻" },
      { id: 1266, name: "Box Drawings Light Down", symbol: "╷" },
      { id: 1267, name: "Vertical Ideographic Iteration Mark", symbol: "〣" },
      { id: 1268, name: "Trigram for Heaven", symbol: "☰" },
      { id: 1269, name: "Trigram for Lake", symbol: "☱" },
      { id: 1270, name: "Trigram for Fire", symbol: "☲" },
      { id: 1271, name: "Trigram for Thunder", symbol: "☳" },
      { id: 1272, name: "Trigram for Wind", symbol: "☴" },
      { id: 1273, name: "Trigram for Water", symbol: "☵" },
      { id: 1274, name: "Trigram for Mountain", symbol: "☶" },
      { id: 1275, name: "Trigram for Earth", symbol: "☷" },
      { id: 1276, name: "Identical To", symbol: "≡" },
      { id: 1277, name: "Multiplication X", symbol: "✕" },
      { id: 1278, name: "Double Horizontal Line", symbol: "═" },
      { id: 1279, name: "Heavy Horizontal Line", symbol: "━" },
      { id: 1280, name: "Light Horizontal Line", symbol: "─" },
      { id: 1281, name: "Double Dash Horizontal Line", symbol: "╍" },
      { id: 1282, name: "Triple Dash Horizontal Line", symbol: "┅" },
      { id: 1283, name: "Heavy Triple Dash Horizontal Line", symbol: "┉" },
      { id: 1284, name: "Light Triple Dash Horizontal Line", symbol: "┄" },
      { id: 1285, name: "Light Quadruple Dash Horizontal Line", symbol: "┈" },
      { id: 1286, name: "Heavy Double Dash Horizontal Line", symbol: "╌" },
      { id: 1287, name: "Light Rightwards Line", symbol: "╴" },
      { id: 1288, name: "Light Leftwards Line", symbol: "╶" },
      { id: 1289, name: "Heavy Rightwards Line", symbol: "╸" },
      { id: 1290, name: "Heavy Leftwards Line", symbol: "╺" },
      { id: 1291, name: "Light Upper Right to Lower Left Line", symbol: "╼" },
      { id: 1292, name: "Light Upper Left to Lower Right Line", symbol: "╾" },
      { id: 1293, name: "Wavy Overline", symbol: "﹉" },
      { id: 1294, name: "Underline", symbol: "﹍" },
      { id: 1295, name: "Double Wavy Overline", symbol: "﹊" },
      { id: 1296, name: "Double Underline", symbol: "﹎" },
      {
        id: 1297,
        name: "Presentation Form For Vertical Low Line",
        symbol: "︲",
      },
      { id: 1298, name: "OCR Hook", symbol: "⑆" },
      { id: 1299, name: "OCR Chair", symbol: "⑇" },
      { id: 1300, name: "OCR Fork", symbol: "⑈" },
      { id: 1301, name: "OCR Inverted Fork", symbol: "⑉" },
      { id: 1302, name: "OCR Belt Buckle", symbol: "⑊" },
      { id: 1303, name: "OCR Bow Tie", symbol: "⑄" },
      { id: 1304, name: "OCR Branch Bank Identification", symbol: "⑀" },
      {
        id: 1305,
        name: "Presentation Form For Vertical Wavy Low Line",
        symbol: "︴",
      },
      { id: 1306, name: "Double Wavy Underline", symbol: "﹏" },
      { id: 1307, name: "Double Overline", symbol: "﹌" },
      { id: 1308, name: "Overline", symbol: "﹋" },
      { id: 1309, name: "Box Drawings Light Diagonal Cross", symbol: "╳" },
      {
        id: 1310,
        name: "Box Drawings Light Diagonal Upper Left to Lower Right",
        symbol: "╲",
      },
      {
        id: 1311,
        name: "Box Drawings Light Diagonal Upper Right to Lower Left",
        symbol: "╱",
      },
      { id: 1312, name: "Bottom Half Parenthesis", symbol: "︶" },
      { id: 1313, name: "Top Half Parenthesis", symbol: "︵" },
      { id: 1314, name: "Vertical Kana Repeat Mark", symbol: "〵" },
      {
        id: 1315,
        name: "Vertical Kana Repeat With Voiced Sound Mark",
        symbol: "〴",
      },
      { id: 1316, name: "Vertical Kana Repeat Mark Upper Half", symbol: "〳" },
      { id: 1317, name: "Vertical Kana Repeat Mark Lower Half", symbol: "〆" },
      { id: 1318, name: "Grave Accent", symbol: "`" },
      { id: 1319, name: "Canadian Syllabics Final Acute", symbol: "ᐟ" },
      { id: 1320, name: "Hyphen", symbol: "‐" },
      { id: 1321, name: "Hyphen Bullet", symbol: "⁃" },
      { id: 1322, name: "Horizontal Line Extension", symbol: "⎯" },
      { id: 1323, name: "JIS Symbol for Enter", symbol: "〄" },
    ],
  },
];
